/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.cpsquoterequest;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class CpsQuoteRequestSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public CpsQuoteRequestSearchOrders orders;
    public CpsQuoteRequestSearchForm form;

    public static class CpsQuoteRequestSearchOrders extends CustomWebElement {
        public OrderBy codiceArea = new OrderBy("cpsQuoteRequest_codiceArea");
        public OrderBy descrizioneArea = new OrderBy("cpsQuoteRequest_descrizioneArea");
        public OrderBy quantitaRichiesta = new OrderBy("cpsQuoteRequest_quantitaRichiesta");
        public OrderBy mm = new OrderBy("cpsQuoteRequest_mm");
        public OrderBy yyyy = new OrderBy("cpsQuoteRequest_yyyy");
        public OrderBy status = new OrderBy("cpsQuoteRequest_status");
        public OrderBy fileId = new OrderBy("cpsQuoteRequest_fileId");
        public OrderBy olo = new OrderBy("cpsQuoteRequest_olo");
    }

    public static class CpsQuoteRequestSearchForm extends SearchForm {
        public StringRange codiceArea = new StringRange("form:codiceArea");
        public Autocomplete descrizioneArea = new Autocomplete("form:descrizioneArea");
        public StringRange quantitaRichiesta = new StringRange("form:quantitaRichiesta");
        public StringRange mm = new StringRange("form:mm");
        public StringRange yyyy = new StringRange("form:yyyy");
        public Autocomplete status = new Autocomplete("form:status");
        public Autocomplete olo = new Autocomplete("form:oloSelector");
        public Autocomplete file = new Autocomplete("form:fileSelector");
    }
}