/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.telecomfilepostfix;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class TelecomFilePostfixSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public TelecomFilePostfixSearchOrders orders;
    public TelecomFilePostfixSearchForm form;

    public static class TelecomFilePostfixSearchOrders extends CustomWebElement {
        public OrderBy id = new OrderBy("telecomFilePostfix_id");
        public OrderBy number = new OrderBy("telecomFilePostfix_number");
        public OrderBy olo = new OrderBy("telecomFilePostfix_olo");
        public OrderBy extension = new OrderBy("telecomFilePostfix_extension");
    }

    public static class TelecomFilePostfixSearchForm extends SearchForm {
        public Autocomplete id = new Autocomplete("form:id");
        public StringRange number = new StringRange("form:number");
        public StringRange olo = new StringRange("form:olo");
        public Autocomplete extension = new Autocomplete("form:extension");
    }
}