/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.BtRequest;
import com.optima.opticarrier.web.domain.support.GenericExcelExporter;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link BtRequest} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class BtRequestExcelExporter extends GenericExcelExporter<BtRequest> {
    @Inject
    protected BtRequestSearchForm sf;

    public BtRequestExcelExporter() {
        super("btRequest_xml", "btRequest_status", "btRequest_dateInsert", "btRequest_fileId");
    }

    @Override
    protected void fillResultItem(int row, BtRequest item) {
        int col = 0;
        setValue(row, col++, item.getXml());
        setValue(row, col++, item.getStatus());
        setDateTime(row, col++, item.getDateInsert());
        setValue(row, col++, item.getFileId());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "btRequest_xml", sf.getXmlSelector());
        setSelector(row++, 0, "btRequest_status", sf.getStatusSelector());
        setRangeDateTime(row++, 0, "btRequest_dateInsert", sf.getDateInsertRange());
        setRangeNumber(row++, 0, "btRequest_fileId", sf.getFileIdRange());
    }
}