/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.CpsDeactivationPrenotification;
import com.optima.opticarrier.web.domain.support.GenericExcelExporter;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link CpsDeactivationPrenotification} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class CpsDeactivationPrenotificationExcelExporter extends GenericExcelExporter<CpsDeactivationPrenotification> {
    @Inject
    protected CpsDeactivationPrenotificationSearchForm sf;

    public CpsDeactivationPrenotificationExcelExporter() {
        super("cpsDeactivationPrenotification_codiceFornitore", "cpsDeactivationPrenotification_codiceOrdineFornitore",
                "cpsDeactivationPrenotification_dataNotifica", "cpsDeactivationPrenotification_dn",
                "cpsDeactivationPrenotification_dataSottoscrizioneContratto", "cpsDeactivationPrenotification_dataPrevistaCessazione");
    }

    @Override
    protected void fillResultItem(int row, CpsDeactivationPrenotification item) {
        int col = 0;
        setValue(row, col++, item.getCodiceFornitore());
        setValue(row, col++, item.getCodiceOrdineFornitore());
        setDateTime(row, col++, item.getDataNotifica());
        setValue(row, col++, item.getDn());
        setDateTime(row, col++, item.getDataSottoscrizioneContratto());
        setDateTime(row, col++, item.getDataPrevistaCessazione());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "cpsDeactivationPrenotification_codiceFornitore", sf.getCodiceFornitoreSelector());
        setSelector(row++, 0, "cpsDeactivationPrenotification_codiceOrdineFornitore", sf.getCodiceOrdineFornitoreSelector());
        setRangeDateTime(row++, 0, "cpsDeactivationPrenotification_dataNotifica", sf.getDataNotificaRange());
        setSelector(row++, 0, "cpsDeactivationPrenotification_dn", sf.getDnSelector());
        setRangeDateTime(row++, 0, "cpsDeactivationPrenotification_dataSottoscrizioneContratto", sf.getDataSottoscrizioneContrattoRange());
        setRangeDateTime(row++, 0, "cpsDeactivationPrenotification_dataPrevistaCessazione", sf.getDataPrevistaCessazioneRange());
        setSelector(row++, 0, "cpsDeactivationPrenotification_cognomeRagSoc", sf.getCognomeRagSocSelector());
        setSelector(row++, 0, "cpsDeactivationPrenotification_nome", sf.getNomeSelector());
        setRangeDateTime(row++, 0, "cpsDeactivationPrenotification_dataRichiestaCessazione", sf.getDataRichiestaCessazioneRange());
        setSelector(row++, 0, "cpsDeactivationPrenotification_status", sf.getStatusSelector());
    }
}