/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.CpsQuoteResponsePenali;
import com.optima.opticarrier.printer.CpsQuoteResponsePenaliPrinter;
import com.optima.opticarrier.repository.CpsQuoteResponsePenaliRepository;
import com.optima.opticarrier.web.domain.support.GenericController;
import com.optima.opticarrier.web.permission.CpsQuoteResponsePenaliPermission;

/**
 * Stateless controller for {@link CpsQuoteResponsePenali} conversation start.
 */
@Named
@Singleton
public class CpsQuoteResponsePenaliController extends GenericController<CpsQuoteResponsePenali, Integer> {
    public static final String CPSQUOTERESPONSEPENALI_EDIT_URI = "/domain/cpsQuoteResponsePenaliEdit.faces";
    public static final String CPSQUOTERESPONSEPENALI_SELECT_URI = "/domain/cpsQuoteResponsePenaliSelect.faces";

    @Inject
    public CpsQuoteResponsePenaliController(CpsQuoteResponsePenaliRepository cpsQuoteResponsePenaliRepository,
            CpsQuoteResponsePenaliPermission cpsQuoteResponsePenaliPermission, CpsQuoteResponsePenaliPrinter cpsQuoteResponsePenaliPrinter) {
        super(cpsQuoteResponsePenaliRepository, cpsQuoteResponsePenaliPermission, cpsQuoteResponsePenaliPrinter, CPSQUOTERESPONSEPENALI_SELECT_URI,
                CPSQUOTERESPONSEPENALI_EDIT_URI);
    }
}