/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import static com.optima.opticarrier.repository.support.PropertySelector.newPropertySelector;
import static com.optima.opticarrier.repository.support.Range.newRange;

import javax.inject.Named;

import com.optima.opticarrier.domain.CpsQuoteResponsePenali;
import com.optima.opticarrier.domain.CpsQuoteResponsePenali_;
import com.optima.opticarrier.domain.OloCps;
import com.optima.opticarrier.domain.SbcFileResponse;
import com.optima.opticarrier.repository.support.PropertySelector;
import com.optima.opticarrier.repository.support.Range;
import com.optima.opticarrier.repository.support.SearchParameters;
import com.optima.opticarrier.web.domain.support.GenericSearchForm;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link CpsQuoteResponsePenali}.
 * It exposes a {@link CpsQuoteResponsePenali} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class CpsQuoteResponsePenaliSearchForm extends GenericSearchForm<CpsQuoteResponsePenali, Integer, CpsQuoteResponsePenaliSearchForm> {
    private static final long serialVersionUID = 1L;
    protected CpsQuoteResponsePenali cpsQuoteResponsePenali = new CpsQuoteResponsePenali();
    protected Range<CpsQuoteResponsePenali, Integer> totVolRichiestiDueMesiPrecRange = newRange(CpsQuoteResponsePenali_.totVolRichiestiDueMesiPrec);
    protected Range<CpsQuoteResponsePenali, Integer> totVolAssegnatiDueMesiPrecRange = newRange(CpsQuoteResponsePenali_.totVolAssegnatiDueMesiPrec);
    protected Range<CpsQuoteResponsePenali, Integer> totVolEffettiviDueMesiPrecRange = newRange(CpsQuoteResponsePenali_.totVolEffettiviDueMesiPrec);
    protected Range<CpsQuoteResponsePenali, Integer> sogliaPenaleRange = newRange(CpsQuoteResponsePenali_.sogliaPenale);
    protected Range<CpsQuoteResponsePenali, Integer> percentualePenaleApplicataRange = newRange(CpsQuoteResponsePenali_.percentualePenaleApplicata);
    protected PropertySelector<CpsQuoteResponsePenali, Integer> totVolRichiestiDueMesiPrecSelector = newPropertySelector(CpsQuoteResponsePenali_.totVolRichiestiDueMesiPrec);
    protected PropertySelector<CpsQuoteResponsePenali, Integer> totVolAssegnatiDueMesiPrecSelector = newPropertySelector(CpsQuoteResponsePenali_.totVolAssegnatiDueMesiPrec);
    protected PropertySelector<CpsQuoteResponsePenali, Integer> totVolEffettiviDueMesiPrecSelector = newPropertySelector(CpsQuoteResponsePenali_.totVolEffettiviDueMesiPrec);
    protected PropertySelector<CpsQuoteResponsePenali, Integer> sogliaPenaleSelector = newPropertySelector(CpsQuoteResponsePenali_.sogliaPenale);
    protected PropertySelector<CpsQuoteResponsePenali, Integer> percentualePenaleApplicataSelector = newPropertySelector(CpsQuoteResponsePenali_.percentualePenaleApplicata);
    protected PropertySelector<CpsQuoteResponsePenali, OloCps> oloSelector = newPropertySelector(CpsQuoteResponsePenali_.olo);
    protected PropertySelector<CpsQuoteResponsePenali, SbcFileResponse> fileSelector = newPropertySelector(CpsQuoteResponsePenali_.file);

    public CpsQuoteResponsePenali getCpsQuoteResponsePenali() {
        return cpsQuoteResponsePenali;
    }

    @Override
    protected CpsQuoteResponsePenali getEntity() {
        return getCpsQuoteResponsePenali();
    }

    @Override
    public CpsQuoteResponsePenaliSearchForm newInstance() {
        return new CpsQuoteResponsePenaliSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(totVolRichiestiDueMesiPrecRange, totVolAssegnatiDueMesiPrecRange, totVolEffettiviDueMesiPrecRange, sogliaPenaleRange,
                percentualePenaleApplicataRange);
        sp.property(totVolRichiestiDueMesiPrecSelector, totVolAssegnatiDueMesiPrecSelector, totVolEffettiviDueMesiPrecSelector, sogliaPenaleSelector,
                percentualePenaleApplicataSelector);
        sp.property(oloSelector, fileSelector);
        return sp;
    }

    @Override
    public void resetWithOther(CpsQuoteResponsePenaliSearchForm other) {
        this.cpsQuoteResponsePenali = other.getCpsQuoteResponsePenali();
        this.totVolRichiestiDueMesiPrecRange = other.getTotVolRichiestiDueMesiPrecRange();
        this.totVolAssegnatiDueMesiPrecRange = other.getTotVolAssegnatiDueMesiPrecRange();
        this.totVolEffettiviDueMesiPrecRange = other.getTotVolEffettiviDueMesiPrecRange();
        this.sogliaPenaleRange = other.getSogliaPenaleRange();
        this.percentualePenaleApplicataRange = other.getPercentualePenaleApplicataRange();
        this.totVolRichiestiDueMesiPrecSelector = other.getTotVolRichiestiDueMesiPrecSelector();
        this.totVolAssegnatiDueMesiPrecSelector = other.getTotVolAssegnatiDueMesiPrecSelector();
        this.totVolEffettiviDueMesiPrecSelector = other.getTotVolEffettiviDueMesiPrecSelector();
        this.sogliaPenaleSelector = other.getSogliaPenaleSelector();
        this.percentualePenaleApplicataSelector = other.getPercentualePenaleApplicataSelector();
        this.oloSelector = other.getOloSelector();
        this.fileSelector = other.getFileSelector();
    }

    // Ranges
    public Range<CpsQuoteResponsePenali, Integer> getTotVolRichiestiDueMesiPrecRange() {
        return totVolRichiestiDueMesiPrecRange;
    }

    public Range<CpsQuoteResponsePenali, Integer> getTotVolAssegnatiDueMesiPrecRange() {
        return totVolAssegnatiDueMesiPrecRange;
    }

    public Range<CpsQuoteResponsePenali, Integer> getTotVolEffettiviDueMesiPrecRange() {
        return totVolEffettiviDueMesiPrecRange;
    }

    public Range<CpsQuoteResponsePenali, Integer> getSogliaPenaleRange() {
        return sogliaPenaleRange;
    }

    public Range<CpsQuoteResponsePenali, Integer> getPercentualePenaleApplicataRange() {
        return percentualePenaleApplicataRange;
    }

    // Property selectors
    public PropertySelector<CpsQuoteResponsePenali, Integer> getTotVolRichiestiDueMesiPrecSelector() {
        return totVolRichiestiDueMesiPrecSelector;
    }

    public PropertySelector<CpsQuoteResponsePenali, Integer> getTotVolAssegnatiDueMesiPrecSelector() {
        return totVolAssegnatiDueMesiPrecSelector;
    }

    public PropertySelector<CpsQuoteResponsePenali, Integer> getTotVolEffettiviDueMesiPrecSelector() {
        return totVolEffettiviDueMesiPrecSelector;
    }

    public PropertySelector<CpsQuoteResponsePenali, Integer> getSogliaPenaleSelector() {
        return sogliaPenaleSelector;
    }

    public PropertySelector<CpsQuoteResponsePenali, Integer> getPercentualePenaleApplicataSelector() {
        return percentualePenaleApplicataSelector;
    }

    // Relation selectors
    public PropertySelector<CpsQuoteResponsePenali, OloCps> getOloSelector() {
        return oloSelector;
    }

    public PropertySelector<CpsQuoteResponsePenali, SbcFileResponse> getFileSelector() {
        return fileSelector;
    }
}
