/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.CpsQuoteResponse;
import com.optima.opticarrier.domain.CpsQuoteResponse_;
import com.optima.opticarrier.domain.OloCps;
import com.optima.opticarrier.domain.SbcFileResponse;
import com.optima.opticarrier.repository.CpsQuoteResponseRepository;
import com.optima.opticarrier.web.domain.support.GenericEditForm;
import com.optima.opticarrier.web.domain.support.GenericToOneAssociation;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link CpsQuoteResponse}.
 */
@Named
@ConversationContextScoped
public class CpsQuoteResponseEditForm extends GenericEditForm<CpsQuoteResponse, Integer> {
    @Inject
    protected CpsQuoteResponseController cpsQuoteResponseController;
    @Inject
    protected SbcFileResponseController sbcFileResponseController;
    protected GenericToOneAssociation<SbcFileResponse, Integer> file;
    @Inject
    protected OloCpsController oloCpsController;
    protected GenericToOneAssociation<OloCps, Integer> olo;

    @Inject
    public CpsQuoteResponseEditForm(CpsQuoteResponseRepository cpsQuoteResponseRepository, CpsQuoteResponseGraphLoader cpsQuoteResponseGraphLoader) {
        super(cpsQuoteResponseRepository, cpsQuoteResponseGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public CpsQuoteResponse getCpsQuoteResponse() {
        return getEntity();
    }

    public String print() {
        return cpsQuoteResponseController.print(getCpsQuoteResponse());
    }

    @PostConstruct
    void setupFileActions() {
        file = new GenericToOneAssociation<SbcFileResponse, Integer>(sbcFileResponseController, CpsQuoteResponse_.file) {
            @Override
            protected SbcFileResponse get() {
                return getCpsQuoteResponse().getFile();
            }

            @Override
            protected void set(SbcFileResponse sbcFileResponse) {
                getCpsQuoteResponse().setFile(sbcFileResponse);
            }
        };
    }

    public GenericToOneAssociation<SbcFileResponse, Integer> getFile() {
        return file;
    }

    @PostConstruct
    void setupOloActions() {
        olo = new GenericToOneAssociation<OloCps, Integer>(oloCpsController, CpsQuoteResponse_.olo) {
            @Override
            protected OloCps get() {
                return getCpsQuoteResponse().getOlo();
            }

            @Override
            protected void set(OloCps oloCps) {
                getCpsQuoteResponse().setOlo(oloCps);
            }
        };
    }

    public GenericToOneAssociation<OloCps, Integer> getOlo() {
        return olo;
    }
}
