/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.CpsQuoteRequest;
import com.optima.opticarrier.web.domain.support.GenericExcelExporter;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link CpsQuoteRequest} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class CpsQuoteRequestExcelExporter extends GenericExcelExporter<CpsQuoteRequest> {
    @Inject
    protected CpsQuoteRequestSearchForm sf;

    public CpsQuoteRequestExcelExporter() {
        super("cpsQuoteRequest_codiceArea", "cpsQuoteRequest_descrizioneArea", "cpsQuoteRequest_quantitaRichiesta", "cpsQuoteRequest_mm",
                "cpsQuoteRequest_yyyy", "cpsQuoteRequest_status");
    }

    @Override
    protected void fillResultItem(int row, CpsQuoteRequest item) {
        int col = 0;
        setValue(row, col++, item.getCodiceArea());
        setValue(row, col++, item.getDescrizioneArea());
        setValue(row, col++, item.getQuantitaRichiesta());
        setValue(row, col++, item.getMm());
        setValue(row, col++, item.getYyyy());
        setValue(row, col++, item.getStatus());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setRangeNumber(row++, 0, "cpsQuoteRequest_codiceArea", sf.getCodiceAreaRange());
        setSelector(row++, 0, "cpsQuoteRequest_descrizioneArea", sf.getDescrizioneAreaSelector());
        setRangeNumber(row++, 0, "cpsQuoteRequest_quantitaRichiesta", sf.getQuantitaRichiestaRange());
        setRangeNumber(row++, 0, "cpsQuoteRequest_mm", sf.getMmRange());
        setRangeNumber(row++, 0, "cpsQuoteRequest_yyyy", sf.getYyyyRange());
        setSelector(row++, 0, "cpsQuoteRequest_status", sf.getStatusSelector());
        setSelectedEntities(row++, 0, "cpsQuoteRequest_file", sf.getFileSelector().getSelected());
        setSelectedEntities(row++, 0, "cpsQuoteRequest_olo", sf.getOloSelector().getSelected());
    }
}