/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.CpsQuoteRequest;
import com.optima.opticarrier.domain.CpsQuoteRequest_;
import com.optima.opticarrier.domain.OloCps;
import com.optima.opticarrier.domain.SbcFileRequest;
import com.optima.opticarrier.repository.CpsQuoteRequestRepository;
import com.optima.opticarrier.web.domain.support.GenericEditForm;
import com.optima.opticarrier.web.domain.support.GenericToOneAssociation;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link CpsQuoteRequest}.
 */
@Named
@ConversationContextScoped
public class CpsQuoteRequestEditForm extends GenericEditForm<CpsQuoteRequest, Integer> {
    @Inject
    protected CpsQuoteRequestController cpsQuoteRequestController;
    @Inject
    protected OloCpsController oloCpsController;
    protected GenericToOneAssociation<OloCps, Integer> olo;
    @Inject
    protected SbcFileRequestController sbcFileRequestController;
    protected GenericToOneAssociation<SbcFileRequest, Integer> file;

    @Inject
    public CpsQuoteRequestEditForm(CpsQuoteRequestRepository cpsQuoteRequestRepository, CpsQuoteRequestGraphLoader cpsQuoteRequestGraphLoader) {
        super(cpsQuoteRequestRepository, cpsQuoteRequestGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public CpsQuoteRequest getCpsQuoteRequest() {
        return getEntity();
    }

    public String print() {
        return cpsQuoteRequestController.print(getCpsQuoteRequest());
    }

    @PostConstruct
    void setupOloActions() {
        olo = new GenericToOneAssociation<OloCps, Integer>(oloCpsController, CpsQuoteRequest_.olo) {
            @Override
            protected OloCps get() {
                return getCpsQuoteRequest().getOlo();
            }

            @Override
            protected void set(OloCps oloCps) {
                getCpsQuoteRequest().setOlo(oloCps);
            }
        };
    }

    public GenericToOneAssociation<OloCps, Integer> getOlo() {
        return olo;
    }

    @PostConstruct
    void setupFileActions() {
        file = new GenericToOneAssociation<SbcFileRequest, Integer>(sbcFileRequestController, CpsQuoteRequest_.file) {
            @Override
            protected SbcFileRequest get() {
                return getCpsQuoteRequest().getFile();
            }

            @Override
            protected void set(SbcFileRequest sbcFileRequest) {
                getCpsQuoteRequest().setFile(sbcFileRequest);
            }
        };
    }

    public GenericToOneAssociation<SbcFileRequest, Integer> getFile() {
        return file;
    }
}
