/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.OloCps;
import com.optima.opticarrier.printer.OloCpsPrinter;
import com.optima.opticarrier.repository.OloCpsRepository;
import com.optima.opticarrier.web.domain.support.GenericController;
import com.optima.opticarrier.web.permission.OloCpsPermission;

/**
 * Stateless controller for {@link OloCps} conversation start.
 */
@Named
@Singleton
public class OloCpsController extends GenericController<OloCps, Integer> {
    public static final String OLOCPS_EDIT_URI = "/domain/oloCpsEdit.faces";
    public static final String OLOCPS_SELECT_URI = "/domain/oloCpsSelect.faces";

    @Inject
    public OloCpsController(OloCpsRepository oloCpsRepository, OloCpsPermission oloCpsPermission, OloCpsPrinter oloCpsPrinter) {
        super(oloCpsRepository, oloCpsPermission, oloCpsPrinter, OLOCPS_SELECT_URI, OLOCPS_EDIT_URI);
    }
}