/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.Prefissi;
import com.optima.opticarrier.web.domain.support.GenericExcelExporter;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Prefissi} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class PrefissiExcelExporter extends GenericExcelExporter<Prefissi> {
    @Inject
    protected PrefissiSearchForm sf;

    public PrefissiExcelExporter() {
        super("prefissi_id", "prefissi_comune", "prefissi_provincia", "prefissi_regione", "prefissi_prefisso", "prefissi_cap");
    }

    @Override
    protected void fillResultItem(int row, Prefissi item) {
        int col = 0;
        setValue(row, col++, item.getId());
        setValue(row, col++, item.getComune());
        setValue(row, col++, item.getProvincia());
        setValue(row, col++, item.getRegione());
        setValue(row, col++, item.getPrefisso());
        setValue(row, col++, item.getCap());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "prefissi_id", sf.getIdSelector());
        setSelector(row++, 0, "prefissi_comune", sf.getComuneSelector());
        setSelector(row++, 0, "prefissi_provincia", sf.getProvinciaSelector());
        setSelector(row++, 0, "prefissi_regione", sf.getRegioneSelector());
        setSelector(row++, 0, "prefissi_prefisso", sf.getPrefissoSelector());
        setSelector(row++, 0, "prefissi_cap", sf.getCapSelector());
        setSelector(row++, 0, "prefissi_codFisco", sf.getCodFiscoSelector());
        setRangeNumber(row++, 0, "prefissi_abitanti", sf.getAbitantiRange());
        setSelector(row++, 0, "prefissi_link", sf.getLinkSelector());
    }
}