/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import static com.optima.opticarrier.repository.support.PropertySelector.newPropertySelector;
import static com.optima.opticarrier.repository.support.Range.newRange;

import javax.inject.Named;

import com.optima.opticarrier.domain.Prefissi;
import com.optima.opticarrier.domain.Prefissi_;
import com.optima.opticarrier.repository.support.PropertySelector;
import com.optima.opticarrier.repository.support.Range;
import com.optima.opticarrier.repository.support.SearchParameters;
import com.optima.opticarrier.web.domain.support.GenericSearchForm;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Prefissi}.
 * It exposes a {@link Prefissi} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class PrefissiSearchForm extends GenericSearchForm<Prefissi, String, PrefissiSearchForm> {
    private static final long serialVersionUID = 1L;
    protected Prefissi prefissi = new Prefissi();
    protected Range<Prefissi, Integer> abitantiRange = newRange(Prefissi_.abitanti);
    protected PropertySelector<Prefissi, String> idSelector = newPropertySelector(Prefissi_.id);
    protected PropertySelector<Prefissi, String> comuneSelector = newPropertySelector(Prefissi_.comune);
    protected PropertySelector<Prefissi, String> provinciaSelector = newPropertySelector(Prefissi_.provincia);
    protected PropertySelector<Prefissi, String> regioneSelector = newPropertySelector(Prefissi_.regione);
    protected PropertySelector<Prefissi, String> prefissoSelector = newPropertySelector(Prefissi_.prefisso);
    protected PropertySelector<Prefissi, String> capSelector = newPropertySelector(Prefissi_.cap);
    protected PropertySelector<Prefissi, String> codFiscoSelector = newPropertySelector(Prefissi_.codFisco);
    protected PropertySelector<Prefissi, Integer> abitantiSelector = newPropertySelector(Prefissi_.abitanti);
    protected PropertySelector<Prefissi, String> linkSelector = newPropertySelector(Prefissi_.link);

    public Prefissi getPrefissi() {
        return prefissi;
    }

    @Override
    protected Prefissi getEntity() {
        return getPrefissi();
    }

    @Override
    public PrefissiSearchForm newInstance() {
        return new PrefissiSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(abitantiRange);
        sp.property(idSelector, comuneSelector, provinciaSelector, regioneSelector, prefissoSelector, capSelector, codFiscoSelector, abitantiSelector,
                linkSelector);
        return sp;
    }

    @Override
    public void resetWithOther(PrefissiSearchForm other) {
        this.prefissi = other.getPrefissi();
        this.abitantiRange = other.getAbitantiRange();
        this.idSelector = other.getIdSelector();
        this.comuneSelector = other.getComuneSelector();
        this.provinciaSelector = other.getProvinciaSelector();
        this.regioneSelector = other.getRegioneSelector();
        this.prefissoSelector = other.getPrefissoSelector();
        this.capSelector = other.getCapSelector();
        this.codFiscoSelector = other.getCodFiscoSelector();
        this.abitantiSelector = other.getAbitantiSelector();
        this.linkSelector = other.getLinkSelector();
    }

    // Ranges
    public Range<Prefissi, Integer> getAbitantiRange() {
        return abitantiRange;
    }

    // Property selectors
    public PropertySelector<Prefissi, String> getIdSelector() {
        return idSelector;
    }

    public PropertySelector<Prefissi, String> getComuneSelector() {
        return comuneSelector;
    }

    public PropertySelector<Prefissi, String> getProvinciaSelector() {
        return provinciaSelector;
    }

    public PropertySelector<Prefissi, String> getRegioneSelector() {
        return regioneSelector;
    }

    public PropertySelector<Prefissi, String> getPrefissoSelector() {
        return prefissoSelector;
    }

    public PropertySelector<Prefissi, String> getCapSelector() {
        return capSelector;
    }

    public PropertySelector<Prefissi, String> getCodFiscoSelector() {
        return codFiscoSelector;
    }

    public PropertySelector<Prefissi, Integer> getAbitantiSelector() {
        return abitantiSelector;
    }

    public PropertySelector<Prefissi, String> getLinkSelector() {
        return linkSelector;
    }
}
