/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.Prefissi;
import com.optima.opticarrier.repository.PrefissiRepository;
import com.optima.opticarrier.web.domain.support.GenericEditForm;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Prefissi}.
 */
@Named
@ConversationContextScoped
public class PrefissiEditForm extends GenericEditForm<Prefissi, String> {
    @Inject
    protected PrefissiController prefissiController;

    @Inject
    public PrefissiEditForm(PrefissiRepository prefissiRepository) {
        super(prefissiRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Prefissi getPrefissi() {
        return getEntity();
    }

    public String print() {
        return prefissiController.print(getPrefissi());
    }
}
