/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcCpsResponse;
import com.optima.opticarrier.printer.SbcCpsResponsePrinter;
import com.optima.opticarrier.repository.SbcCpsResponseRepository;
import com.optima.opticarrier.web.domain.support.GenericController;
import com.optima.opticarrier.web.permission.SbcCpsResponsePermission;

/**
 * Stateless controller for {@link SbcCpsResponse} conversation start.
 */
@Named
@Singleton
public class SbcCpsResponseController extends GenericController<SbcCpsResponse, Integer> {
    public static final String SBCCPSRESPONSE_EDIT_URI = "/domain/sbcCpsResponseEdit.faces";
    public static final String SBCCPSRESPONSE_SELECT_URI = "/domain/sbcCpsResponseSelect.faces";

    @Inject
    public SbcCpsResponseController(SbcCpsResponseRepository sbcCpsResponseRepository, SbcCpsResponsePermission sbcCpsResponsePermission,
            SbcCpsResponsePrinter sbcCpsResponsePrinter) {
        super(sbcCpsResponseRepository, sbcCpsResponsePermission, sbcCpsResponsePrinter, SBCCPSRESPONSE_SELECT_URI, SBCCPSRESPONSE_EDIT_URI);
    }
}