/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import static com.optima.opticarrier.repository.support.PropertySelector.newPropertySelector;
import static com.optima.opticarrier.repository.support.Range.newRange;

import java.util.Date;

import javax.inject.Named;

import com.optima.opticarrier.domain.SbcFileResponse;
import com.optima.opticarrier.domain.SbcFileResponse_;
import com.optima.opticarrier.repository.support.PropertySelector;
import com.optima.opticarrier.repository.support.Range;
import com.optima.opticarrier.repository.support.SearchParameters;
import com.optima.opticarrier.web.domain.support.GenericSearchForm;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link SbcFileResponse}.
 * It exposes a {@link SbcFileResponse} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class SbcFileResponseSearchForm extends GenericSearchForm<SbcFileResponse, Integer, SbcFileResponseSearchForm> {
    private static final long serialVersionUID = 1L;
    protected SbcFileResponse sbcFileResponse = new SbcFileResponse();
    protected Range<SbcFileResponse, Date> dataCreazioneRange = newRange(SbcFileResponse_.dataCreazione);
    protected PropertySelector<SbcFileResponse, String> nomeFileSelector = newPropertySelector(SbcFileResponse_.nomeFile);
    protected PropertySelector<SbcFileResponse, String> oloSelector = newPropertySelector(SbcFileResponse_.olo);
    protected PropertySelector<SbcFileResponse, String> statoSelector = newPropertySelector(SbcFileResponse_.stato);

    public SbcFileResponse getSbcFileResponse() {
        return sbcFileResponse;
    }

    @Override
    protected SbcFileResponse getEntity() {
        return getSbcFileResponse();
    }

    @Override
    public SbcFileResponseSearchForm newInstance() {
        return new SbcFileResponseSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(dataCreazioneRange);
        sp.property(nomeFileSelector, oloSelector, statoSelector);
        return sp;
    }

    @Override
    public void resetWithOther(SbcFileResponseSearchForm other) {
        this.sbcFileResponse = other.getSbcFileResponse();
        this.dataCreazioneRange = other.getDataCreazioneRange();
        this.nomeFileSelector = other.getNomeFileSelector();
        this.oloSelector = other.getOloSelector();
        this.statoSelector = other.getStatoSelector();
    }

    // Ranges
    public Range<SbcFileResponse, Date> getDataCreazioneRange() {
        return dataCreazioneRange;
    }

    // Property selectors
    public PropertySelector<SbcFileResponse, String> getNomeFileSelector() {
        return nomeFileSelector;
    }

    public PropertySelector<SbcFileResponse, String> getOloSelector() {
        return oloSelector;
    }

    public PropertySelector<SbcFileResponse, String> getStatoSelector() {
        return statoSelector;
    }
}
