/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import static com.optima.opticarrier.repository.support.PropertySelector.newPropertySelector;
import static com.optima.opticarrier.repository.support.Range.newRange;

import java.util.Date;

import javax.inject.Named;

import com.optima.opticarrier.domain.SbcFileRequest;
import com.optima.opticarrier.domain.SbcFileRequest_;
import com.optima.opticarrier.repository.support.PropertySelector;
import com.optima.opticarrier.repository.support.Range;
import com.optima.opticarrier.repository.support.SearchParameters;
import com.optima.opticarrier.web.domain.support.GenericSearchForm;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link SbcFileRequest}.
 * It exposes a {@link SbcFileRequest} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class SbcFileRequestSearchForm extends GenericSearchForm<SbcFileRequest, Integer, SbcFileRequestSearchForm> {
    private static final long serialVersionUID = 1L;
    protected SbcFileRequest sbcFileRequest = new SbcFileRequest();
    protected Range<SbcFileRequest, Date> dataCreazioneRange = newRange(SbcFileRequest_.dataCreazione);
    protected Range<SbcFileRequest, Integer> rowNumberRange = newRange(SbcFileRequest_.rowNumber);
    protected PropertySelector<SbcFileRequest, String> nomeFileSelector = newPropertySelector(SbcFileRequest_.nomeFile);
    protected PropertySelector<SbcFileRequest, String> oloSelector = newPropertySelector(SbcFileRequest_.olo);
    protected PropertySelector<SbcFileRequest, String> statoSelector = newPropertySelector(SbcFileRequest_.stato);
    protected PropertySelector<SbcFileRequest, Integer> rowNumberSelector = newPropertySelector(SbcFileRequest_.rowNumber);
    protected PropertySelector<SbcFileRequest, String> statusSelector = newPropertySelector(SbcFileRequest_.status);

    public SbcFileRequest getSbcFileRequest() {
        return sbcFileRequest;
    }

    @Override
    protected SbcFileRequest getEntity() {
        return getSbcFileRequest();
    }

    @Override
    public SbcFileRequestSearchForm newInstance() {
        return new SbcFileRequestSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(dataCreazioneRange, rowNumberRange);
        sp.property(nomeFileSelector, oloSelector, statoSelector, rowNumberSelector, statusSelector);
        return sp;
    }

    @Override
    public void resetWithOther(SbcFileRequestSearchForm other) {
        this.sbcFileRequest = other.getSbcFileRequest();
        this.dataCreazioneRange = other.getDataCreazioneRange();
        this.rowNumberRange = other.getRowNumberRange();
        this.nomeFileSelector = other.getNomeFileSelector();
        this.oloSelector = other.getOloSelector();
        this.statoSelector = other.getStatoSelector();
        this.rowNumberSelector = other.getRowNumberSelector();
        this.statusSelector = other.getStatusSelector();
    }

    // Ranges
    public Range<SbcFileRequest, Date> getDataCreazioneRange() {
        return dataCreazioneRange;
    }

    public Range<SbcFileRequest, Integer> getRowNumberRange() {
        return rowNumberRange;
    }

    // Property selectors
    public PropertySelector<SbcFileRequest, String> getNomeFileSelector() {
        return nomeFileSelector;
    }

    public PropertySelector<SbcFileRequest, String> getOloSelector() {
        return oloSelector;
    }

    public PropertySelector<SbcFileRequest, String> getStatoSelector() {
        return statoSelector;
    }

    public PropertySelector<SbcFileRequest, Integer> getRowNumberSelector() {
        return rowNumberSelector;
    }

    public PropertySelector<SbcFileRequest, String> getStatusSelector() {
        return statusSelector;
    }
}
