/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.SbcWlrResponse;
import com.optima.opticarrier.web.domain.support.GenericExcelExporter;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link SbcWlrResponse} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class SbcWlrResponseExcelExporter extends GenericExcelExporter<SbcWlrResponse> {
    @Inject
    protected SbcWlrResponseSearchForm sf;

    public SbcWlrResponseExcelExporter() {
        super("sbcWlrResponse_tipoNotifica", "sbcWlrResponse_dataEstrazioneWL", "sbcWlrResponse_borchiaISDN", "sbcWlrResponse_codicePiattaforma",
                "sbcWlrResponse_dataAttivazione", "sbcWlrResponse_dataValidazioneFormaleContrattua");
    }

    @Override
    protected void fillResultItem(int row, SbcWlrResponse item) {
        int col = 0;
        setValue(row, col++, item.getTipoNotifica());
        setValue(row, col++, item.getDataEstrazioneWL());
        setValue(row, col++, item.getBorchiaISDN());
        setValue(row, col++, item.getCodicePiattaforma());
        setValue(row, col++, item.getDataAttivazione());
        setValue(row, col++, item.getDataValidazioneFormaleContrattua());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "sbcWlrResponse_tipoNotifica", sf.getTipoNotificaSelector());
        setRangeDate(row++, 0, "sbcWlrResponse_dataEstrazioneWL", sf.getDataEstrazioneWLRange());
        setSelector(row++, 0, "sbcWlrResponse_borchiaISDN", sf.getBorchiaISDNSelector());
        setSelector(row++, 0, "sbcWlrResponse_codicePiattaforma", sf.getCodicePiattaformaSelector());
        setRangeDate(row++, 0, "sbcWlrResponse_dataAttivazione", sf.getDataAttivazioneRange());
        setRangeDate(row++, 0, "sbcWlrResponse_dataValidazioneFormaleContrattua", sf.getDataValidazioneFormaleContrattuaRange());
        setRangeDate(row++, 0, "sbcWlrResponse_dataValidazioneTecnicoGestionale", sf.getDataValidazioneTecnicoGestionaleRange());
        setSelector(row++, 0, "sbcWlrResponse_dn", sf.getDnSelector());
        setSelector(row++, 0, "sbcWlrResponse_flagLineaBtsNaked", sf.getFlagLineaBtsNakedSelector());
        setSelector(row++, 0, "sbcWlrResponse_note", sf.getNoteSelector());
        setSelector(row++, 0, "sbcWlrResponse_nuovoDN", sf.getNuovoDNSelector());
        setSelector(row++, 0, "sbcWlrResponse_cognomeReferente", sf.getCognomeReferenteSelector());
        setSelector(row++, 0, "sbcWlrResponse_nomeReferente", sf.getNomeReferenteSelector());
        setSelector(row++, 0, "sbcWlrResponse_qualificaRef", sf.getQualificaRefSelector());
        setSelector(row++, 0, "sbcWlrResponse_telefonoFissoReferente", sf.getTelefonoFissoReferenteSelector());
        setSelector(row++, 0, "sbcWlrResponse_telefonoMobileReferente", sf.getTelefonoMobileReferenteSelector());
        setSelector(row++, 0, "sbcWlrResponse_codiceMotivoRifiuto", sf.getCodiceMotivoRifiutoSelector());
        setSelector(row++, 0, "sbcWlrResponse_motivoRifiuto", sf.getMotivoRifiutoSelector());
        setSelector(row++, 0, "sbcWlrResponse_tipoCausaleRifiuto", sf.getTipoCausaleRifiutoSelector());
        setSelector(row++, 0, "sbcWlrResponse_tipoDn", sf.getTipoDnSelector());
        setSelector(row++, 0, "sbcWlrResponse_tipoLinea", sf.getTipoLineaSelector());
        setSelector(row++, 0, "sbcWlrResponse_codiceCausaleAccodamento", sf.getCodiceCausaleAccodamentoSelector());
        setRangeDate(row++, 0, "sbcWlrResponse_dataPrevistaSoluzione", sf.getDataPrevistaSoluzioneRange());
        setSelector(row++, 0, "sbcWlrResponse_descrizioneCausaleAccodamento", sf.getDescrizioneCausaleAccodamentoSelector());
        setSelector(row++, 0, "sbcWlrResponse_dimensioneCoda", sf.getDimensioneCodaSelector());
        setSelector(row++, 0, "sbcWlrResponse_posizioneCoda", sf.getPosizioneCodaSelector());
        setSelector(row++, 0, "sbcWlrResponse_codiceCausaleAnnullamento", sf.getCodiceCausaleAnnullamentoSelector());
        setRangeDate(row++, 0, "sbcWlrResponse_taAnnullamento", sf.getTaAnnullamentoRange());
        setSelector(row++, 0, "sbcWlrResponse_descrizioneCausaleAnnullamento", sf.getDescrizioneCausaleAnnullamentoSelector());
        setRangeDateTime(row++, 0, "sbcWlrResponse_dataEspletamento", sf.getDataEspletamentoRange());
        setRangeDate(row++, 0, "sbcWlrResponse_dataContatto", sf.getDataContattoRange());
        setSelector(row++, 0, "sbcWlrResponse_nuovaDA", sf.getNuovaDASelector());
        setSelector(row++, 0, "sbcWlrResponse_oraAppuntamento", sf.getOraAppuntamentoSelector());
        setSelector(row++, 0, "sbcWlrResponse_oraContatto", sf.getOraContattoSelector());
        setSelector(row++, 0, "sbcWlrResponse_referenteContattato", sf.getReferenteContattatoSelector());
        setSelector(row++, 0, "sbcWlrResponse_telefonoReferenteContattato", sf.getTelefonoReferenteContattatoSelector());
        setRangeDate(row++, 0, "sbcWlrResponse_taInizioLavorazione", sf.getTaInizioLavorazioneRange());
        setSelector(row++, 0, "sbcWlrResponse_fasciaOraria", sf.getFasciaOrariaSelector());
        setSelector(row++, 0, "sbcWlrResponse_nuovaDAC", sf.getNuovaDACSelector());
        setSelector(row++, 0, "sbcWlrResponse_flagPermessi", sf.getFlagPermessiSelector());
        setSelector(row++, 0, "sbcWlrResponse_giorniPrevisti", sf.getGiorniPrevistiSelector());
        setSelector(row++, 0, "sbcWlrResponse_codiceCausaleRimodulazione", sf.getCodiceCausaleRimodulazioneSelector());
        setSelector(row++, 0, "sbcWlrResponse_descrizioneCausaleRimodulazione", sf.getDescrizioneCausaleRimodulazioneSelector());
        setSelector(row++, 0, "sbcWlrResponse_nuovaDataPrevistaSoluzione", sf.getNuovaDataPrevistaSoluzioneSelector());
        setSelector(row++, 0, "sbcWlrResponse_codiceCausaleSospensione", sf.getCodiceCausaleSospensioneSelector());
        setRangeDate(row++, 0, "sbcWlrResponse_dataSospensione", sf.getDataSospensioneRange());
        setSelector(row++, 0, "sbcWlrResponse_descrizioneCausale", sf.getDescrizioneCausaleSelector());
        setSelector(row++, 0, "sbcWlrResponse_codiceFornitore", sf.getCodiceFornitoreSelector());
        setSelector(row++, 0, "sbcWlrResponse_codiceOrdineFornitore", sf.getCodiceOrdineFornitoreSelector());
        setRangeDate(row++, 0, "sbcWlrResponse_dataDRO", sf.getDataDRORange());
        setRangeDate(row++, 0, "sbcWlrResponse_dataNotifica", sf.getDataNotificaRange());
        setSelector(row++, 0, "sbcWlrResponse_statoOrdine", sf.getStatoOrdineSelector());
        setSelector(row++, 0, "sbcWlrResponse_codiceOrdineRichiedente", sf.getCodiceOrdineRichiedenteSelector());
        setSelectedEntities(row++, 0, "sbcWlrResponse_file", sf.getFileSelector().getSelected());
        setSelectedEntities(row++, 0, "sbcWlrResponse_olo", sf.getOloSelector().getSelected());
        setSelector(row++, 0, "sbcWlrResponse_variation", sf.getVariationSelector());
    }
}