/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcWlrRequest;
import com.optima.opticarrier.repository.SbcWlrRequestRepository;
import com.optima.opticarrier.repository.support.EntityGraphLoader;

/**
 * Preloads the {@link SbcWlrRequest} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class SbcWlrRequestGraphLoader extends EntityGraphLoader<SbcWlrRequest, Integer> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected SbcWlrRequestGraphLoader() {
        super();
    }

    @Inject
    public SbcWlrRequestGraphLoader(SbcWlrRequestRepository sbcWlrRequestRepository) {
        super(sbcWlrRequestRepository);
    }

    @Override
    public void loadGraph(SbcWlrRequest sbcWlrRequest) {
        loadSingular(sbcWlrRequest.getOlo());
        loadSingular(sbcWlrRequest.getFile());
    }
}