/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.OloCps;
import com.optima.opticarrier.domain.SbcFileResponse;
import com.optima.opticarrier.domain.SbcWlrResponse;
import com.optima.opticarrier.domain.SbcWlrResponse_;
import com.optima.opticarrier.repository.SbcWlrResponseRepository;
import com.optima.opticarrier.web.domain.support.GenericEditForm;
import com.optima.opticarrier.web.domain.support.GenericToOneAssociation;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SbcWlrResponse}.
 */
@Named
@ConversationContextScoped
public class SbcWlrResponseEditForm extends GenericEditForm<SbcWlrResponse, Integer> {
    @Inject
    protected SbcWlrResponseController sbcWlrResponseController;
    @Inject
    protected OloCpsController oloCpsController;
    protected GenericToOneAssociation<OloCps, Integer> olo;
    @Inject
    protected SbcFileResponseController sbcFileResponseController;
    protected GenericToOneAssociation<SbcFileResponse, Integer> file;

    @Inject
    public SbcWlrResponseEditForm(SbcWlrResponseRepository sbcWlrResponseRepository, SbcWlrResponseGraphLoader sbcWlrResponseGraphLoader) {
        super(sbcWlrResponseRepository, sbcWlrResponseGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public SbcWlrResponse getSbcWlrResponse() {
        return getEntity();
    }

    public String print() {
        return sbcWlrResponseController.print(getSbcWlrResponse());
    }

    @PostConstruct
    void setupOloActions() {
        olo = new GenericToOneAssociation<OloCps, Integer>(oloCpsController, SbcWlrResponse_.olo) {
            @Override
            protected OloCps get() {
                return getSbcWlrResponse().getOlo();
            }

            @Override
            protected void set(OloCps oloCps) {
                getSbcWlrResponse().setOlo(oloCps);
            }
        };
    }

    public GenericToOneAssociation<OloCps, Integer> getOlo() {
        return olo;
    }

    @PostConstruct
    void setupFileActions() {
        file = new GenericToOneAssociation<SbcFileResponse, Integer>(sbcFileResponseController, SbcWlrResponse_.file) {
            @Override
            protected SbcFileResponse get() {
                return getSbcWlrResponse().getFile();
            }

            @Override
            protected void set(SbcFileResponse sbcFileResponse) {
                getSbcWlrResponse().setFile(sbcFileResponse);
            }
        };
    }

    public GenericToOneAssociation<SbcFileResponse, Integer> getFile() {
        return file;
    }
}
