/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcWlrResponse;
import com.optima.opticarrier.printer.SbcWlrResponsePrinter;
import com.optima.opticarrier.repository.SbcWlrResponseRepository;
import com.optima.opticarrier.web.domain.support.GenericController;
import com.optima.opticarrier.web.permission.SbcWlrResponsePermission;

/**
 * Stateless controller for {@link SbcWlrResponse} conversation start.
 */
@Named
@Singleton
public class SbcWlrResponseController extends GenericController<SbcWlrResponse, Integer> {
    public static final String SBCWLRRESPONSE_EDIT_URI = "/domain/sbcWlrResponseEdit.faces";
    public static final String SBCWLRRESPONSE_SELECT_URI = "/domain/sbcWlrResponseSelect.faces";

    @Inject
    public SbcWlrResponseController(SbcWlrResponseRepository sbcWlrResponseRepository, SbcWlrResponsePermission sbcWlrResponsePermission,
            SbcWlrResponsePrinter sbcWlrResponsePrinter) {
        super(sbcWlrResponseRepository, sbcWlrResponsePermission, sbcWlrResponsePrinter, SBCWLRRESPONSE_SELECT_URI, SBCWLRRESPONSE_EDIT_URI);
    }
}