/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcWlrRequest;
import com.optima.opticarrier.domain.SbcWlrRequest_;
import com.optima.opticarrier.printer.SbcWlrRequestPrinter;
import com.optima.opticarrier.repository.SbcWlrRequestRepository;
import com.optima.opticarrier.repository.support.SearchParameters;
import com.optima.opticarrier.web.domain.support.GenericController;
import com.optima.opticarrier.web.permission.SbcWlrRequestPermission;

/**
 * Stateless controller for {@link SbcWlrRequest} conversation start.
 */
@Named
@Singleton
public class SbcWlrRequestController extends GenericController<SbcWlrRequest, Integer> {
    public static final String SBCWLRREQUEST_EDIT_URI = "/domain/sbcWlrRequestEdit.faces";
    public static final String SBCWLRREQUEST_SELECT_URI = "/domain/sbcWlrRequestSelect.faces";

    @Inject
    public SbcWlrRequestController(SbcWlrRequestRepository sbcWlrRequestRepository, SbcWlrRequestPermission sbcWlrRequestPermission,
            SbcWlrRequestPrinter sbcWlrRequestPrinter) {
        super(sbcWlrRequestRepository, sbcWlrRequestPermission, sbcWlrRequestPrinter, SBCWLRREQUEST_SELECT_URI, SBCWLRREQUEST_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(SbcWlrRequest_.progressivoRichiesta);
    }
}