/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.OloCps;
import com.optima.opticarrier.domain.SbcFileRequest;
import com.optima.opticarrier.domain.SbcWlrRequest;
import com.optima.opticarrier.domain.SbcWlrRequest_;
import com.optima.opticarrier.repository.SbcWlrRequestRepository;
import com.optima.opticarrier.web.domain.support.GenericEditForm;
import com.optima.opticarrier.web.domain.support.GenericToOneAssociation;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SbcWlrRequest}.
 */
@Named
@ConversationContextScoped
public class SbcWlrRequestEditForm extends GenericEditForm<SbcWlrRequest, Integer> {
    @Inject
    protected SbcWlrRequestController sbcWlrRequestController;
    @Inject
    protected OloCpsController oloCpsController;
    protected GenericToOneAssociation<OloCps, Integer> olo;
    @Inject
    protected SbcFileRequestController sbcFileRequestController;
    protected GenericToOneAssociation<SbcFileRequest, Integer> file;

    @Inject
    public SbcWlrRequestEditForm(SbcWlrRequestRepository sbcWlrRequestRepository, SbcWlrRequestGraphLoader sbcWlrRequestGraphLoader) {
        super(sbcWlrRequestRepository, sbcWlrRequestGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public SbcWlrRequest getSbcWlrRequest() {
        return getEntity();
    }

    public String print() {
        return sbcWlrRequestController.print(getSbcWlrRequest());
    }

    @PostConstruct
    void setupOloActions() {
        olo = new GenericToOneAssociation<OloCps, Integer>(oloCpsController, SbcWlrRequest_.olo) {
            @Override
            protected OloCps get() {
                return getSbcWlrRequest().getOlo();
            }

            @Override
            protected void set(OloCps oloCps) {
                getSbcWlrRequest().setOlo(oloCps);
            }
        };
    }

    public GenericToOneAssociation<OloCps, Integer> getOlo() {
        return olo;
    }

    @PostConstruct
    void setupFileActions() {
        file = new GenericToOneAssociation<SbcFileRequest, Integer>(sbcFileRequestController, SbcWlrRequest_.file) {
            @Override
            protected SbcFileRequest get() {
                return getSbcWlrRequest().getFile();
            }

            @Override
            protected void set(SbcFileRequest sbcFileRequest) {
                getSbcWlrRequest().setFile(sbcFileRequest);
            }
        };
    }

    public GenericToOneAssociation<SbcFileRequest, Integer> getFile() {
        return file;
    }
}
