/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import static com.optima.opticarrier.repository.support.PropertySelector.newPropertySelector;
import static com.optima.opticarrier.repository.support.Range.newRange;

import javax.inject.Named;

import com.optima.opticarrier.domain.TelecomFilePostfix;
import com.optima.opticarrier.domain.TelecomFilePostfix_;
import com.optima.opticarrier.repository.support.PropertySelector;
import com.optima.opticarrier.repository.support.Range;
import com.optima.opticarrier.repository.support.SearchParameters;
import com.optima.opticarrier.web.domain.support.GenericSearchForm;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link TelecomFilePostfix}.
 * It exposes a {@link TelecomFilePostfix} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class TelecomFilePostfixSearchForm extends GenericSearchForm<TelecomFilePostfix, String, TelecomFilePostfixSearchForm> {
    private static final long serialVersionUID = 1L;
    protected TelecomFilePostfix telecomFilePostfix = new TelecomFilePostfix();
    protected Range<TelecomFilePostfix, Integer> numberRange = newRange(TelecomFilePostfix_.number);
    protected Range<TelecomFilePostfix, Integer> oloRange = newRange(TelecomFilePostfix_.olo);
    protected PropertySelector<TelecomFilePostfix, String> idSelector = newPropertySelector(TelecomFilePostfix_.id);
    protected PropertySelector<TelecomFilePostfix, Integer> numberSelector = newPropertySelector(TelecomFilePostfix_.number);
    protected PropertySelector<TelecomFilePostfix, Integer> oloSelector = newPropertySelector(TelecomFilePostfix_.olo);
    protected PropertySelector<TelecomFilePostfix, String> extensionSelector = newPropertySelector(TelecomFilePostfix_.extension);

    public TelecomFilePostfix getTelecomFilePostfix() {
        return telecomFilePostfix;
    }

    @Override
    protected TelecomFilePostfix getEntity() {
        return getTelecomFilePostfix();
    }

    @Override
    public TelecomFilePostfixSearchForm newInstance() {
        return new TelecomFilePostfixSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(numberRange, oloRange);
        sp.property(idSelector, numberSelector, oloSelector, extensionSelector);
        return sp;
    }

    @Override
    public void resetWithOther(TelecomFilePostfixSearchForm other) {
        this.telecomFilePostfix = other.getTelecomFilePostfix();
        this.numberRange = other.getNumberRange();
        this.oloRange = other.getOloRange();
        this.idSelector = other.getIdSelector();
        this.numberSelector = other.getNumberSelector();
        this.oloSelector = other.getOloSelector();
        this.extensionSelector = other.getExtensionSelector();
    }

    // Ranges
    public Range<TelecomFilePostfix, Integer> getNumberRange() {
        return numberRange;
    }

    public Range<TelecomFilePostfix, Integer> getOloRange() {
        return oloRange;
    }

    // Property selectors
    public PropertySelector<TelecomFilePostfix, String> getIdSelector() {
        return idSelector;
    }

    public PropertySelector<TelecomFilePostfix, Integer> getNumberSelector() {
        return numberSelector;
    }

    public PropertySelector<TelecomFilePostfix, Integer> getOloSelector() {
        return oloSelector;
    }

    public PropertySelector<TelecomFilePostfix, String> getExtensionSelector() {
        return extensionSelector;
    }
}
