/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.optima.opticarrier.domain.SbcWlrRequest;
import com.optima.opticarrier.domain.WlrRequestAggiuntivis;
import com.optima.opticarrier.domain.WlrRequestAggiuntivis_;
import com.optima.opticarrier.repository.WlrRequestAggiuntivisRepository;
import com.optima.opticarrier.web.domain.support.GenericEditForm;
import com.optima.opticarrier.web.domain.support.GenericToOneAssociation;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link WlrRequestAggiuntivis}.
 */
@Named
@ConversationContextScoped
public class WlrRequestAggiuntivisEditForm extends GenericEditForm<WlrRequestAggiuntivis, Integer> {
    @Inject
    protected WlrRequestAggiuntivisController wlrRequestAggiuntivisController;
    @Inject
    protected SbcWlrRequestController sbcWlrRequestController;
    protected GenericToOneAssociation<SbcWlrRequest, Integer> request;

    @Inject
    public WlrRequestAggiuntivisEditForm(WlrRequestAggiuntivisRepository wlrRequestAggiuntivisRepository,
            WlrRequestAggiuntivisGraphLoader wlrRequestAggiuntivisGraphLoader) {
        super(wlrRequestAggiuntivisRepository, wlrRequestAggiuntivisGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public WlrRequestAggiuntivis getWlrRequestAggiuntivis() {
        return getEntity();
    }

    public String print() {
        return wlrRequestAggiuntivisController.print(getWlrRequestAggiuntivis());
    }

    @PostConstruct
    void setupRequestActions() {
        request = new GenericToOneAssociation<SbcWlrRequest, Integer>(sbcWlrRequestController, WlrRequestAggiuntivis_.request) {
            @Override
            protected SbcWlrRequest get() {
                return getWlrRequestAggiuntivis().getRequest();
            }

            @Override
            protected void set(SbcWlrRequest sbcWlrRequest) {
                getWlrRequestAggiuntivis().setRequest(sbcWlrRequest);
            }
        };
    }

    public GenericToOneAssociation<SbcWlrRequest, Integer> getRequest() {
        return request;
    }
}
