/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import static com.optima.opticarrier.repository.support.PropertySelector.newPropertySelector;

import javax.inject.Named;

import com.optima.opticarrier.domain.SbcWlrRequest;
import com.optima.opticarrier.domain.WlrRequestAggiuntivis;
import com.optima.opticarrier.domain.WlrRequestAggiuntivis_;
import com.optima.opticarrier.repository.support.PropertySelector;
import com.optima.opticarrier.repository.support.SearchParameters;
import com.optima.opticarrier.web.domain.support.GenericSearchForm;
import com.optima.opticarrier.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link WlrRequestAggiuntivis}.
 * It exposes a {@link WlrRequestAggiuntivis} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class WlrRequestAggiuntivisSearchForm extends GenericSearchForm<WlrRequestAggiuntivis, Integer, WlrRequestAggiuntivisSearchForm> {
    private static final long serialVersionUID = 1L;
    protected WlrRequestAggiuntivis wlrRequestAggiuntivis = new WlrRequestAggiuntivis();
    protected PropertySelector<WlrRequestAggiuntivis, String> aggiuntiviSelector = newPropertySelector(WlrRequestAggiuntivis_.aggiuntivi);
    protected PropertySelector<WlrRequestAggiuntivis, Boolean> completedSelector = newPropertySelector(WlrRequestAggiuntivis_.completed);
    protected PropertySelector<WlrRequestAggiuntivis, SbcWlrRequest> requestSelector = newPropertySelector(WlrRequestAggiuntivis_.request);

    public WlrRequestAggiuntivis getWlrRequestAggiuntivis() {
        return wlrRequestAggiuntivis;
    }

    @Override
    protected WlrRequestAggiuntivis getEntity() {
        return getWlrRequestAggiuntivis();
    }

    @Override
    public WlrRequestAggiuntivisSearchForm newInstance() {
        return new WlrRequestAggiuntivisSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.property(aggiuntiviSelector, completedSelector);
        sp.property(requestSelector);
        return sp;
    }

    @Override
    public void resetWithOther(WlrRequestAggiuntivisSearchForm other) {
        this.wlrRequestAggiuntivis = other.getWlrRequestAggiuntivis();
        this.aggiuntiviSelector = other.getAggiuntiviSelector();
        this.completedSelector = other.getCompletedSelector();
        this.requestSelector = other.getRequestSelector();
    }

    // Property selectors
    public PropertySelector<WlrRequestAggiuntivis, String> getAggiuntiviSelector() {
        return aggiuntiviSelector;
    }

    public PropertySelector<WlrRequestAggiuntivis, Boolean> getCompletedSelector() {
        return completedSelector;
    }

    // Relation selectors
    public PropertySelector<WlrRequestAggiuntivis, SbcWlrRequest> getRequestSelector() {
        return requestSelector;
    }
}
