/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 */
package com.optima.opticarrier.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.WlrServiceCode;
import com.optima.opticarrier.printer.WlrServiceCodePrinter;
import com.optima.opticarrier.repository.WlrServiceCodeRepository;
import com.optima.opticarrier.web.domain.support.GenericController;
import com.optima.opticarrier.web.permission.WlrServiceCodePermission;

/**
 * Stateless controller for {@link WlrServiceCode} conversation start.
 */
@Named
@Singleton
public class WlrServiceCodeController extends GenericController<WlrServiceCode, String> {
    public static final String WLRSERVICECODE_EDIT_URI = "/domain/wlrServiceCodeEdit.faces";
    public static final String WLRSERVICECODE_SELECT_URI = "/domain/wlrServiceCodeSelect.faces";

    @Inject
    public WlrServiceCodeController(WlrServiceCodeRepository wlrServiceCodeRepository, WlrServiceCodePermission wlrServiceCodePermission,
            WlrServiceCodePrinter wlrServiceCodePrinter) {
        super(wlrServiceCodeRepository, wlrServiceCodePermission, wlrServiceCodePrinter, WLRSERVICECODE_SELECT_URI, WLRSERVICECODE_EDIT_URI);
    }
}