/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.sbcfileresponse;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class SbcFileResponseSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public SbcFileResponseSearchOrders orders;
    public SbcFileResponseSearchForm form;

    public static class SbcFileResponseSearchOrders extends CustomWebElement {
        public OrderBy nomeFile = new OrderBy("sbcFileResponse_nomeFile");
        public OrderBy dataCreazione = new OrderBy("sbcFileResponse_dataCreazione");
        public OrderBy olo = new OrderBy("sbcFileResponse_olo");
        public OrderBy stato = new OrderBy("sbcFileResponse_stato");
    }

    public static class SbcFileResponseSearchForm extends SearchForm {
        public Autocomplete nomeFile = new Autocomplete("form:nomeFile");
        public StringRange dataCreazione = new StringRange("form:dataCreazione");
        public Autocomplete olo = new Autocomplete("form:olo");
        public Autocomplete stato = new Autocomplete("form:stato");
    }
}