/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.sbcwlrresponse;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.ManyBooleans;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class SbcWlrResponseSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public SbcWlrResponseSearchOrders orders;
    public SbcWlrResponseSearchForm form;

    public static class SbcWlrResponseSearchOrders extends CustomWebElement {
        public OrderBy tipoNotifica = new OrderBy("sbcWlrResponse_tipoNotifica");
        public OrderBy dataEstrazioneWL = new OrderBy("sbcWlrResponse_dataEstrazioneWL");
        public OrderBy borchiaISDN = new OrderBy("sbcWlrResponse_borchiaISDN");
        public OrderBy codicePiattaforma = new OrderBy("sbcWlrResponse_codicePiattaforma");
        public OrderBy dataAttivazione = new OrderBy("sbcWlrResponse_dataAttivazione");
        public OrderBy dataValidazioneFormaleContrattua = new OrderBy("sbcWlrResponse_dataValidazioneFormaleContrattua");
        public OrderBy dataValidazioneTecnicoGestionale = new OrderBy("sbcWlrResponse_dataValidazioneTecnicoGestionale");
        public OrderBy dn = new OrderBy("sbcWlrResponse_dn");
        public OrderBy flagLineaBtsNaked = new OrderBy("sbcWlrResponse_flagLineaBtsNaked");
        public OrderBy note = new OrderBy("sbcWlrResponse_note");
        public OrderBy nuovoDN = new OrderBy("sbcWlrResponse_nuovoDN");
        public OrderBy cognomeReferente = new OrderBy("sbcWlrResponse_cognomeReferente");
        public OrderBy nomeReferente = new OrderBy("sbcWlrResponse_nomeReferente");
        public OrderBy qualificaRef = new OrderBy("sbcWlrResponse_qualificaRef");
        public OrderBy telefonoFissoReferente = new OrderBy("sbcWlrResponse_telefonoFissoReferente");
        public OrderBy telefonoMobileReferente = new OrderBy("sbcWlrResponse_telefonoMobileReferente");
        public OrderBy codiceMotivoRifiuto = new OrderBy("sbcWlrResponse_codiceMotivoRifiuto");
        public OrderBy motivoRifiuto = new OrderBy("sbcWlrResponse_motivoRifiuto");
        public OrderBy tipoCausaleRifiuto = new OrderBy("sbcWlrResponse_tipoCausaleRifiuto");
        public OrderBy tipoDn = new OrderBy("sbcWlrResponse_tipoDn");
        public OrderBy tipoLinea = new OrderBy("sbcWlrResponse_tipoLinea");
        public OrderBy codiceCausaleAccodamento = new OrderBy("sbcWlrResponse_codiceCausaleAccodamento");
        public OrderBy dataPrevistaSoluzione = new OrderBy("sbcWlrResponse_dataPrevistaSoluzione");
        public OrderBy descrizioneCausaleAccodamento = new OrderBy("sbcWlrResponse_descrizioneCausaleAccodamento");
        public OrderBy dimensioneCoda = new OrderBy("sbcWlrResponse_dimensioneCoda");
        public OrderBy posizioneCoda = new OrderBy("sbcWlrResponse_posizioneCoda");
        public OrderBy codiceCausaleAnnullamento = new OrderBy("sbcWlrResponse_codiceCausaleAnnullamento");
        public OrderBy taAnnullamento = new OrderBy("sbcWlrResponse_taAnnullamento");
        public OrderBy descrizioneCausaleAnnullamento = new OrderBy("sbcWlrResponse_descrizioneCausaleAnnullamento");
        public OrderBy dataEspletamento = new OrderBy("sbcWlrResponse_dataEspletamento");
        public OrderBy dataContatto = new OrderBy("sbcWlrResponse_dataContatto");
        public OrderBy nuovaDA = new OrderBy("sbcWlrResponse_nuovaDA");
        public OrderBy oraAppuntamento = new OrderBy("sbcWlrResponse_oraAppuntamento");
        public OrderBy oraContatto = new OrderBy("sbcWlrResponse_oraContatto");
        public OrderBy referenteContattato = new OrderBy("sbcWlrResponse_referenteContattato");
        public OrderBy telefonoReferenteContattato = new OrderBy("sbcWlrResponse_telefonoReferenteContattato");
        public OrderBy taInizioLavorazione = new OrderBy("sbcWlrResponse_taInizioLavorazione");
        public OrderBy fasciaOraria = new OrderBy("sbcWlrResponse_fasciaOraria");
        public OrderBy nuovaDAC = new OrderBy("sbcWlrResponse_nuovaDAC");
        public OrderBy flagPermessi = new OrderBy("sbcWlrResponse_flagPermessi");
        public OrderBy giorniPrevisti = new OrderBy("sbcWlrResponse_giorniPrevisti");
        public OrderBy codiceCausaleRimodulazione = new OrderBy("sbcWlrResponse_codiceCausaleRimodulazione");
        public OrderBy descrizioneCausaleRimodulazione = new OrderBy("sbcWlrResponse_descrizioneCausaleRimodulazione");
        public OrderBy nuovaDataPrevistaSoluzione = new OrderBy("sbcWlrResponse_nuovaDataPrevistaSoluzione");
        public OrderBy codiceCausaleSospensione = new OrderBy("sbcWlrResponse_codiceCausaleSospensione");
        public OrderBy dataSospensione = new OrderBy("sbcWlrResponse_dataSospensione");
        public OrderBy descrizioneCausale = new OrderBy("sbcWlrResponse_descrizioneCausale");
        public OrderBy codiceFornitore = new OrderBy("sbcWlrResponse_codiceFornitore");
        public OrderBy codiceOrdineFornitore = new OrderBy("sbcWlrResponse_codiceOrdineFornitore");
        public OrderBy dataDRO = new OrderBy("sbcWlrResponse_dataDRO");
        public OrderBy dataNotifica = new OrderBy("sbcWlrResponse_dataNotifica");
        public OrderBy statoOrdine = new OrderBy("sbcWlrResponse_statoOrdine");
        public OrderBy codiceOrdineRichiedente = new OrderBy("sbcWlrResponse_codiceOrdineRichiedente");
        public OrderBy fileId = new OrderBy("sbcWlrResponse_fileId");
        public OrderBy olo = new OrderBy("sbcWlrResponse_olo");
        public OrderBy variation = new OrderBy("sbcWlrResponse_variation");
    }

    public static class SbcWlrResponseSearchForm extends SearchForm {
        public Autocomplete tipoNotifica = new Autocomplete("form:tipoNotifica");
        public StringRange dataEstrazioneWL = new StringRange("form:dataEstrazioneWL");
        public Autocomplete borchiaISDN = new Autocomplete("form:borchiaISDN");
        public Autocomplete codicePiattaforma = new Autocomplete("form:codicePiattaforma");
        public StringRange dataAttivazione = new StringRange("form:dataAttivazione");
        public StringRange dataValidazioneFormaleContrattua = new StringRange("form:dataValidazioneFormaleContrattua");
        public StringRange dataValidazioneTecnicoGestionale = new StringRange("form:dataValidazioneTecnicoGestionale");
        public Autocomplete dn = new Autocomplete("form:dn");
        public Autocomplete flagLineaBtsNaked = new Autocomplete("form:flagLineaBtsNaked");
        public Autocomplete note = new Autocomplete("form:note");
        public Autocomplete nuovoDN = new Autocomplete("form:nuovoDN");
        public Autocomplete cognomeReferente = new Autocomplete("form:cognomeReferente");
        public Autocomplete nomeReferente = new Autocomplete("form:nomeReferente");
        public Autocomplete qualificaRef = new Autocomplete("form:qualificaRef");
        public Autocomplete telefonoFissoReferente = new Autocomplete("form:telefonoFissoReferente");
        public Autocomplete telefonoMobileReferente = new Autocomplete("form:telefonoMobileReferente");
        public Autocomplete codiceMotivoRifiuto = new Autocomplete("form:codiceMotivoRifiuto");
        public Autocomplete motivoRifiuto = new Autocomplete("form:motivoRifiuto");
        public Autocomplete tipoCausaleRifiuto = new Autocomplete("form:tipoCausaleRifiuto");
        public Autocomplete tipoDn = new Autocomplete("form:tipoDn");
        public Autocomplete tipoLinea = new Autocomplete("form:tipoLinea");
        public Autocomplete codiceCausaleAccodamento = new Autocomplete("form:codiceCausaleAccodamento");
        public StringRange dataPrevistaSoluzione = new StringRange("form:dataPrevistaSoluzione");
        public Autocomplete descrizioneCausaleAccodamento = new Autocomplete("form:descrizioneCausaleAccodamento");
        public Autocomplete dimensioneCoda = new Autocomplete("form:dimensioneCoda");
        public Autocomplete posizioneCoda = new Autocomplete("form:posizioneCoda");
        public Autocomplete codiceCausaleAnnullamento = new Autocomplete("form:codiceCausaleAnnullamento");
        public StringRange taAnnullamento = new StringRange("form:taAnnullamento");
        public Autocomplete descrizioneCausaleAnnullamento = new Autocomplete("form:descrizioneCausaleAnnullamento");
        public StringRange dataEspletamento = new StringRange("form:dataEspletamento");
        public StringRange dataContatto = new StringRange("form:dataContatto");
        public Autocomplete nuovaDA = new Autocomplete("form:nuovaDA");
        public Autocomplete oraAppuntamento = new Autocomplete("form:oraAppuntamento");
        public Autocomplete oraContatto = new Autocomplete("form:oraContatto");
        public Autocomplete referenteContattato = new Autocomplete("form:referenteContattato");
        public Autocomplete telefonoReferenteContattato = new Autocomplete("form:telefonoReferenteContattato");
        public StringRange taInizioLavorazione = new StringRange("form:taInizioLavorazione");
        public Autocomplete fasciaOraria = new Autocomplete("form:fasciaOraria");
        public Autocomplete nuovaDAC = new Autocomplete("form:nuovaDAC");
        public Autocomplete flagPermessi = new Autocomplete("form:flagPermessi");
        public Autocomplete giorniPrevisti = new Autocomplete("form:giorniPrevisti");
        public Autocomplete codiceCausaleRimodulazione = new Autocomplete("form:codiceCausaleRimodulazione");
        public Autocomplete descrizioneCausaleRimodulazione = new Autocomplete("form:descrizioneCausaleRimodulazione");
        public Autocomplete nuovaDataPrevistaSoluzione = new Autocomplete("form:nuovaDataPrevistaSoluzione");
        public Autocomplete codiceCausaleSospensione = new Autocomplete("form:codiceCausaleSospensione");
        public StringRange dataSospensione = new StringRange("form:dataSospensione");
        public Autocomplete descrizioneCausale = new Autocomplete("form:descrizioneCausale");
        public Autocomplete codiceFornitore = new Autocomplete("form:codiceFornitore");
        public Autocomplete codiceOrdineFornitore = new Autocomplete("form:codiceOrdineFornitore");
        public StringRange dataDRO = new StringRange("form:dataDRO");
        public StringRange dataNotifica = new StringRange("form:dataNotifica");
        public Autocomplete statoOrdine = new Autocomplete("form:statoOrdine");
        public Autocomplete codiceOrdineRichiedente = new Autocomplete("form:codiceOrdineRichiedente");
        public ManyBooleans variation = new ManyBooleans("form:variation");
        public Autocomplete olo = new Autocomplete("form:oloSelector");
        public Autocomplete file = new Autocomplete("form:fileSelector");
    }
}