/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.cpsquoteresponsepenali;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EditAction;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.IntegerInput;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.NoInverseManyToOne;

@Page
public class CpsQuoteResponsePenaliEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public CpsQuoteResponsePenaliEditForm form;
    public CpsQuoteResponsePenaliEditTabs tabs;

    public static class CpsQuoteResponsePenaliEditForm extends CustomWebElement {
        public IntegerInput totVolRichiestiDueMesiPrec = new IntegerInput("form:totVolRichiestiDueMesiPrec");
        public IntegerInput totVolAssegnatiDueMesiPrec = new IntegerInput("form:totVolAssegnatiDueMesiPrec");
        public IntegerInput totVolEffettiviDueMesiPrec = new IntegerInput("form:totVolEffettiviDueMesiPrec");
        public IntegerInput sogliaPenale = new IntegerInput("form:sogliaPenale");
        public IntegerInput percentualePenaleApplicata = new IntegerInput("form:percentualePenaleApplicata");

        public NoInverseManyToOne olo = new NoInverseManyToOne("form:olo");

        public NoInverseManyToOne file = new NoInverseManyToOne("form:file");
    };

    public static class CpsQuoteResponsePenaliEditTabs extends CustomWebElement {
    };
}