/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.response;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Checkbox;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EditAction;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.IntegerInput;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.StringInput;

@Page
public class ResponseEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public ResponseEditForm form;
    public ResponseEditTabs tabs;

    public static class ResponseEditForm extends CustomWebElement {
        public IntegerInput idSBC = new IntegerInput("form:idSBC");
        public IntegerInput actionType = new IntegerInput("form:actionType");
        public StringInput dataCambiamentoStato = new StringInput("form:dataCambiamentoStato");
        public StringInput codiceErrore = new StringInput("form:codiceErrore");
        public StringInput descrizioneErrore = new StringInput("form:descrizioneErrore");
        public StringInput nomeFileDiOrigineRichiesta = new StringInput("form:nomeFileDiOrigineRichiesta");
        public StringInput progressivoRichiesta = new StringInput("form:progressivoRichiesta");
        public StringInput dataSpedizioneFile = new StringInput("form:dataSpedizioneFile");
        public StringInput tipoOperazione = new StringInput("form:tipoOperazione");
        public StringInput tipoServizio = new StringInput("form:tipoServizio");
        public StringInput tipoLinea = new StringInput("form:tipoLinea");
        public StringInput tipoAttivazione = new StringInput("form:tipoAttivazione");
        public StringInput numeroLinee = new StringInput("form:numeroLinee");
        public StringInput cli = new StringInput("form:cli");
        public StringInput tipoNotifica = new StringInput("form:tipoNotifica");
        public StringInput statoOrdine = new StringInput("form:statoOrdine");
        public StringInput type = new StringInput("form:type");
        public StringInput dn = new StringInput("form:dn");
        public StringInput dataEsplitamento = new StringInput("form:dataEsplitamento");
        public StringInput codiceCausaleAnnullamento = new StringInput("form:codiceCausaleAnnullamento");
        public StringInput descrizioneCausaleAnnullamento = new StringInput("form:descrizioneCausaleAnnullamento");
        public StringInput dataAnnullamento = new StringInput("form:dataAnnullamento");
        public StringInput codiceCausaleSospensione = new StringInput("form:codiceCausaleSospensione");
        public StringInput descrizioneCausale = new StringInput("form:descrizioneCausale");
        public StringInput dataSospensione = new StringInput("form:dataSospensione");
        public IntegerInput batchId = new IntegerInput("form:batchId");
        public IntegerInput oloId = new IntegerInput("form:oloId");
        public Checkbox variation = new Checkbox("form:variation");
        public StringInput responseCode = new StringInput("form:responseCode");
        public StringInput responseDesc = new StringInput("form:responseDesc");
    };

    public static class ResponseEditTabs extends CustomWebElement {
    };
}