/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.response;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.ManyBooleans;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class ResponseSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public ResponseSearchOrders orders;
    public ResponseSearchForm form;

    public static class ResponseSearchOrders extends CustomWebElement {
        public OrderBy idSBC = new OrderBy("response_idSBC");
        public OrderBy actionType = new OrderBy("response_actionType");
        public OrderBy dataCambiamentoStato = new OrderBy("response_dataCambiamentoStato");
        public OrderBy codiceErrore = new OrderBy("response_codiceErrore");
        public OrderBy descrizioneErrore = new OrderBy("response_descrizioneErrore");
        public OrderBy nomeFileDiOrigineRichiesta = new OrderBy("response_nomeFileDiOrigineRichiesta");
        public OrderBy progressivoRichiesta = new OrderBy("response_progressivoRichiesta");
        public OrderBy dataSpedizioneFile = new OrderBy("response_dataSpedizioneFile");
        public OrderBy tipoOperazione = new OrderBy("response_tipoOperazione");
        public OrderBy tipoServizio = new OrderBy("response_tipoServizio");
        public OrderBy tipoLinea = new OrderBy("response_tipoLinea");
        public OrderBy tipoAttivazione = new OrderBy("response_tipoAttivazione");
        public OrderBy numeroLinee = new OrderBy("response_numeroLinee");
        public OrderBy cli = new OrderBy("response_cli");
        public OrderBy tipoNotifica = new OrderBy("response_tipoNotifica");
        public OrderBy statoOrdine = new OrderBy("response_statoOrdine");
        public OrderBy type = new OrderBy("response_type");
        public OrderBy dn = new OrderBy("response_dn");
        public OrderBy dataEsplitamento = new OrderBy("response_dataEsplitamento");
        public OrderBy codiceCausaleAnnullamento = new OrderBy("response_codiceCausaleAnnullamento");
        public OrderBy descrizioneCausaleAnnullamento = new OrderBy("response_descrizioneCausaleAnnullamento");
        public OrderBy dataAnnullamento = new OrderBy("response_dataAnnullamento");
        public OrderBy codiceCausaleSospensione = new OrderBy("response_codiceCausaleSospensione");
        public OrderBy descrizioneCausale = new OrderBy("response_descrizioneCausale");
        public OrderBy dataSospensione = new OrderBy("response_dataSospensione");
        public OrderBy batchId = new OrderBy("response_batchId");
        public OrderBy oloId = new OrderBy("response_oloId");
        public OrderBy variation = new OrderBy("response_variation");
        public OrderBy responseCode = new OrderBy("response_responseCode");
        public OrderBy responseDesc = new OrderBy("response_responseDesc");
    }

    public static class ResponseSearchForm extends SearchForm {
        public StringRange idSBC = new StringRange("form:idSBC");
        public StringRange actionType = new StringRange("form:actionType");
        public Autocomplete dataCambiamentoStato = new Autocomplete("form:dataCambiamentoStato");
        public Autocomplete codiceErrore = new Autocomplete("form:codiceErrore");
        public Autocomplete descrizioneErrore = new Autocomplete("form:descrizioneErrore");
        public Autocomplete nomeFileDiOrigineRichiesta = new Autocomplete("form:nomeFileDiOrigineRichiesta");
        public Autocomplete progressivoRichiesta = new Autocomplete("form:progressivoRichiesta");
        public Autocomplete dataSpedizioneFile = new Autocomplete("form:dataSpedizioneFile");
        public Autocomplete tipoOperazione = new Autocomplete("form:tipoOperazione");
        public Autocomplete tipoServizio = new Autocomplete("form:tipoServizio");
        public Autocomplete tipoLinea = new Autocomplete("form:tipoLinea");
        public Autocomplete tipoAttivazione = new Autocomplete("form:tipoAttivazione");
        public Autocomplete numeroLinee = new Autocomplete("form:numeroLinee");
        public Autocomplete cli = new Autocomplete("form:cli");
        public Autocomplete tipoNotifica = new Autocomplete("form:tipoNotifica");
        public Autocomplete statoOrdine = new Autocomplete("form:statoOrdine");
        public Autocomplete type = new Autocomplete("form:type");
        public Autocomplete dn = new Autocomplete("form:dn");
        public Autocomplete dataEsplitamento = new Autocomplete("form:dataEsplitamento");
        public Autocomplete codiceCausaleAnnullamento = new Autocomplete("form:codiceCausaleAnnullamento");
        public Autocomplete descrizioneCausaleAnnullamento = new Autocomplete("form:descrizioneCausaleAnnullamento");
        public Autocomplete dataAnnullamento = new Autocomplete("form:dataAnnullamento");
        public Autocomplete codiceCausaleSospensione = new Autocomplete("form:codiceCausaleSospensione");
        public Autocomplete descrizioneCausale = new Autocomplete("form:descrizioneCausale");
        public Autocomplete dataSospensione = new Autocomplete("form:dataSospensione");
        public StringRange batchId = new StringRange("form:batchId");
        public StringRange oloId = new StringRange("form:oloId");
        public ManyBooleans variation = new ManyBooleans("form:variation");
        public Autocomplete responseCode = new Autocomplete("form:responseCode");
        public Autocomplete responseDesc = new Autocomplete("form:responseDesc");
    }
}