/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.sbcwlrrequestvariation;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Checkbox;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.DateInput;
import com.optima.opticarrier.web.selenium.support.elements.EditAction;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.IntegerInput;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.NoInverseManyToOne;
import com.optima.opticarrier.web.selenium.support.elements.StringInput;

@Page
public class SbcWlrRequestVariationEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public SbcWlrRequestVariationEditForm form;
    public SbcWlrRequestVariationEditTabs tabs;

    public static class SbcWlrRequestVariationEditForm extends CustomWebElement {
        public StringInput progressiveRichiesta = new StringInput("form:progressiveRichiesta");
        public IntegerInput actionType = new IntegerInput("form:actionType");
        public IntegerInput wlrType = new IntegerInput("form:wlrType");
        public StringInput dn = new StringInput("form:dn");
        public DateInput dataSottoscrizioneContratto = new DateInput("form:dataSottoscrizioneContratto");
        public StringInput customerSurname = new StringInput("form:customerSurname");
        public StringInput serviceNumber = new StringInput("form:serviceNumber");
        public StringInput numberAdditional = new StringInput("form:numberAdditional");
        public StringInput codicePrestazione = new StringInput("form:codicePrestazione");
        public StringInput aggiuntivo1 = new StringInput("form:aggiuntivo1");
        public StringInput aggiuntivo2 = new StringInput("form:aggiuntivo2");
        public StringInput aggiuntivo3 = new StringInput("form:aggiuntivo3");
        public StringInput aggiuntivo4 = new StringInput("form:aggiuntivo4");
        public StringInput aggiuntivo5 = new StringInput("form:aggiuntivo5");
        public StringInput aggiuntivo6 = new StringInput("form:aggiuntivo6");
        public StringInput aggiuntivo7 = new StringInput("form:aggiuntivo7");
        public StringInput codeMove = new StringInput("form:codeMove");
        public StringInput lineNumber = new StringInput("form:lineNumber");
        public StringInput directionality = new StringInput("form:directionality");
        public StringInput codeDriveType = new StringInput("form:codeDriveType");
        public StringInput status = new StringInput("form:status");
        public IntegerInput waits = new IntegerInput("form:waits");
        public Checkbox elaborated = new Checkbox("form:elaborated");

        public NoInverseManyToOne olo = new NoInverseManyToOne("form:olo");

        public NoInverseManyToOne file = new NoInverseManyToOne("form:file");
    };

    public static class SbcWlrRequestVariationEditTabs extends CustomWebElement {
    };
}