/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.sbcwlrrequestvariation;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.ManyBooleans;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class SbcWlrRequestVariationSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public SbcWlrRequestVariationSearchOrders orders;
    public SbcWlrRequestVariationSearchForm form;

    public static class SbcWlrRequestVariationSearchOrders extends CustomWebElement {
        public OrderBy progressiveRichiesta = new OrderBy("sbcWlrRequestVariation_progressiveRichiesta");
        public OrderBy actionType = new OrderBy("sbcWlrRequestVariation_actionType");
        public OrderBy wlrType = new OrderBy("sbcWlrRequestVariation_wlrType");
        public OrderBy dn = new OrderBy("sbcWlrRequestVariation_dn");
        public OrderBy dataSottoscrizioneContratto = new OrderBy("sbcWlrRequestVariation_dataSottoscrizioneContratto");
        public OrderBy customerSurname = new OrderBy("sbcWlrRequestVariation_customerSurname");
        public OrderBy serviceNumber = new OrderBy("sbcWlrRequestVariation_serviceNumber");
        public OrderBy numberAdditional = new OrderBy("sbcWlrRequestVariation_numberAdditional");
        public OrderBy codicePrestazione = new OrderBy("sbcWlrRequestVariation_codicePrestazione");
        public OrderBy aggiuntivo1 = new OrderBy("sbcWlrRequestVariation_aggiuntivo1");
        public OrderBy aggiuntivo2 = new OrderBy("sbcWlrRequestVariation_aggiuntivo2");
        public OrderBy aggiuntivo3 = new OrderBy("sbcWlrRequestVariation_aggiuntivo3");
        public OrderBy aggiuntivo4 = new OrderBy("sbcWlrRequestVariation_aggiuntivo4");
        public OrderBy aggiuntivo5 = new OrderBy("sbcWlrRequestVariation_aggiuntivo5");
        public OrderBy aggiuntivo6 = new OrderBy("sbcWlrRequestVariation_aggiuntivo6");
        public OrderBy aggiuntivo7 = new OrderBy("sbcWlrRequestVariation_aggiuntivo7");
        public OrderBy codeMove = new OrderBy("sbcWlrRequestVariation_codeMove");
        public OrderBy lineNumber = new OrderBy("sbcWlrRequestVariation_lineNumber");
        public OrderBy directionality = new OrderBy("sbcWlrRequestVariation_directionality");
        public OrderBy codeDriveType = new OrderBy("sbcWlrRequestVariation_codeDriveType");
        public OrderBy fileId = new OrderBy("sbcWlrRequestVariation_fileId");
        public OrderBy olo = new OrderBy("sbcWlrRequestVariation_olo");
        public OrderBy status = new OrderBy("sbcWlrRequestVariation_status");
        public OrderBy waits = new OrderBy("sbcWlrRequestVariation_waits");
        public OrderBy elaborated = new OrderBy("sbcWlrRequestVariation_elaborated");
    }

    public static class SbcWlrRequestVariationSearchForm extends SearchForm {
        public Autocomplete progressiveRichiesta = new Autocomplete("form:progressiveRichiesta");
        public StringRange actionType = new StringRange("form:actionType");
        public StringRange wlrType = new StringRange("form:wlrType");
        public Autocomplete dn = new Autocomplete("form:dn");
        public StringRange dataSottoscrizioneContratto = new StringRange("form:dataSottoscrizioneContratto");
        public Autocomplete customerSurname = new Autocomplete("form:customerSurname");
        public Autocomplete serviceNumber = new Autocomplete("form:serviceNumber");
        public Autocomplete numberAdditional = new Autocomplete("form:numberAdditional");
        public Autocomplete codicePrestazione = new Autocomplete("form:codicePrestazione");
        public Autocomplete aggiuntivo1 = new Autocomplete("form:aggiuntivo1");
        public Autocomplete aggiuntivo2 = new Autocomplete("form:aggiuntivo2");
        public Autocomplete aggiuntivo3 = new Autocomplete("form:aggiuntivo3");
        public Autocomplete aggiuntivo4 = new Autocomplete("form:aggiuntivo4");
        public Autocomplete aggiuntivo5 = new Autocomplete("form:aggiuntivo5");
        public Autocomplete aggiuntivo6 = new Autocomplete("form:aggiuntivo6");
        public Autocomplete aggiuntivo7 = new Autocomplete("form:aggiuntivo7");
        public Autocomplete codeMove = new Autocomplete("form:codeMove");
        public Autocomplete lineNumber = new Autocomplete("form:lineNumber");
        public Autocomplete directionality = new Autocomplete("form:directionality");
        public Autocomplete codeDriveType = new Autocomplete("form:codeDriveType");
        public Autocomplete status = new Autocomplete("form:status");
        public StringRange waits = new StringRange("form:waits");
        public ManyBooleans elaborated = new ManyBooleans("form:elaborated");
        public Autocomplete olo = new Autocomplete("form:oloSelector");
        public Autocomplete file = new Autocomplete("form:fileSelector");
    }
}