/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.cpsdeactivationnotification;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class CpsDeactivationNotificationSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public CpsDeactivationNotificationSearchOrders orders;
    public CpsDeactivationNotificationSearchForm form;

    public static class CpsDeactivationNotificationSearchOrders extends CustomWebElement {
        public OrderBy codiceFornitore = new OrderBy("cpsDeactivationNotification_codiceFornitore");
        public OrderBy dataNotifica = new OrderBy("cpsDeactivationNotification_dataNotifica");
        public OrderBy dn = new OrderBy("cpsDeactivationNotification_dn");
        public OrderBy dataSottoscrizioneContratto = new OrderBy("cpsDeactivationNotification_dataSottoscrizioneContratto");
        public OrderBy codiceMotivoRifiuto = new OrderBy("cpsDeactivationNotification_codiceMotivoRifiuto");
        public OrderBy dataEsplitamento = new OrderBy("cpsDeactivationNotification_dataEsplitamento");
        public OrderBy motivoRifiuto = new OrderBy("cpsDeactivationNotification_motivoRifiuto");
        public OrderBy status = new OrderBy("cpsDeactivationNotification_status");
    }

    public static class CpsDeactivationNotificationSearchForm extends SearchForm {
        public Autocomplete codiceFornitore = new Autocomplete("form:codiceFornitore");
        public StringRange dataNotifica = new StringRange("form:dataNotifica");
        public Autocomplete dn = new Autocomplete("form:dn");
        public Autocomplete dataSottoscrizioneContratto = new Autocomplete("form:dataSottoscrizioneContratto");
        public Autocomplete codiceMotivoRifiuto = new Autocomplete("form:codiceMotivoRifiuto");
        public StringRange dataEsplitamento = new StringRange("form:dataEsplitamento");
        public Autocomplete motivoRifiuto = new Autocomplete("form:motivoRifiuto");
        public Autocomplete status = new Autocomplete("form:status");
    }
}