/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/HomePage.p.vm.java
 */
package com.optima.opticarrier.web.selenium.page;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.WebClient;

@Page
public class HomePage {
    @FindBy(id = "form:home_link")
    public WebElement home;
    @FindBy(id = "form:selectBtRequests")
    public WebElement btRequestsLink;
    @FindBy(id = "form:selectCpsDeactivationNotifications")
    public WebElement cpsDeactivationNotificationsLink;
    @FindBy(id = "form:selectCpsDeactivationPrenotifications")
    public WebElement cpsDeactivationPrenotificationsLink;
    @FindBy(id = "form:selectCpsQuoteRequests")
    public WebElement cpsQuoteRequestsLink;
    @FindBy(id = "form:selectCpsQuoteResponses")
    public WebElement cpsQuoteResponsesLink;
    @FindBy(id = "form:selectCpsQuoteResponsePenalis")
    public WebElement cpsQuoteResponsePenalisLink;
    @FindBy(id = "form:selectOloCpss")
    public WebElement oloCpssLink;
    @FindBy(id = "form:selectPrefissis")
    public WebElement prefissisLink;
    @FindBy(id = "form:selectResponses")
    public WebElement responsesLink;
    @FindBy(id = "form:selectSbcCpsRequests")
    public WebElement sbcCpsRequestsLink;
    @FindBy(id = "form:selectSbcCpsResponses")
    public WebElement sbcCpsResponsesLink;
    @FindBy(id = "form:selectSbcFileRequests")
    public WebElement sbcFileRequestsLink;
    @FindBy(id = "form:selectSbcFileResponses")
    public WebElement sbcFileResponsesLink;
    @FindBy(id = "form:selectSbcWlrRequests")
    public WebElement sbcWlrRequestsLink;
    @FindBy(id = "form:selectSbcWlrRequestVariations")
    public WebElement sbcWlrRequestVariationsLink;
    @FindBy(id = "form:selectSbcWlrResponses")
    public WebElement sbcWlrResponsesLink;
    @FindBy(id = "form:selectTelecomFilePostfixes")
    public WebElement telecomFilePostfixesLink;
    @FindBy(id = "form:selectWlrRequestAggiuntiviss")
    public WebElement wlrRequestAggiuntivissLink;
    @FindBy(id = "form:selectWlrServiceCodes")
    public WebElement wlrServiceCodesLink;
    @FindBy(id = "form:selectWlrTraslocoCodes")
    public WebElement wlrTraslocoCodesLink;
    @FindBy(id = "form:switchToFrench")
    public WebElement switchToFrench;
    @FindBy(id = "form:switchToEnglish")
    public WebElement switchToEnglish;
    @FindBy(id = "form:messages")
    public WebElement messagesPanel;

    protected WebClient webClient;

    public void home() {
        webClient.click(home);
    }

    public void switchToEnglish() {
        webClient.click(switchToEnglish);
    }

    public void switchToFrench() {
        webClient.click(switchToFrench);
    }

    public void btRequests() {
        webClient.click(btRequestsLink);
    }

    public void cpsDeactivationNotifications() {
        webClient.click(cpsDeactivationNotificationsLink);
    }

    public void cpsDeactivationPrenotifications() {
        webClient.click(cpsDeactivationPrenotificationsLink);
    }

    public void cpsQuoteRequests() {
        webClient.click(cpsQuoteRequestsLink);
    }

    public void cpsQuoteResponses() {
        webClient.click(cpsQuoteResponsesLink);
    }

    public void cpsQuoteResponsePenalis() {
        webClient.click(cpsQuoteResponsePenalisLink);
    }

    public void oloCpss() {
        webClient.click(oloCpssLink);
    }

    public void prefissis() {
        webClient.click(prefissisLink);
    }

    public void responses() {
        webClient.click(responsesLink);
    }

    public void sbcCpsRequests() {
        webClient.click(sbcCpsRequestsLink);
    }

    public void sbcCpsResponses() {
        webClient.click(sbcCpsResponsesLink);
    }

    public void sbcFileRequests() {
        webClient.click(sbcFileRequestsLink);
    }

    public void sbcFileResponses() {
        webClient.click(sbcFileResponsesLink);
    }

    public void sbcWlrRequests() {
        webClient.click(sbcWlrRequestsLink);
    }

    public void sbcWlrRequestVariations() {
        webClient.click(sbcWlrRequestVariationsLink);
    }

    public void sbcWlrResponses() {
        webClient.click(sbcWlrResponsesLink);
    }

    public void telecomFilePostfixes() {
        webClient.click(telecomFilePostfixesLink);
    }

    public void wlrRequestAggiuntiviss() {
        webClient.click(wlrRequestAggiuntivissLink);
    }

    public void wlrServiceCodes() {
        webClient.click(wlrServiceCodesLink);
    }

    public void wlrTraslocoCodes() {
        webClient.click(wlrTraslocoCodesLink);
    }

    public void hasText(String... values) {
        for (String value : values) {
            webClient.waitUntilTextIsPresent(value);
        }
    }

    public void hasMessage(String... values) {
        for (String value : values) {
            webClient.waitUntilTextIsPresent(messagesPanel, value);
        }
    }

    protected void clickEdit(String value) {
        webClient.clickLinkTitle("Edit " + value);
    }

    protected void clickAdd(String value) {
        webClient.clickLinkTitle("Add " + value);
    }

    protected void clickDelete(String value) {
        webClient.clickLinkTitle("Delete " + value);
    }

    protected void clickRemove(String value) {
        webClient.clickLinkTitle("Remove " + value);
    }

    protected void clickSelect(String value) {
        webClient.clickLinkTitle("Select " + value);
    }
}