/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.wlrservicecode;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EditAction;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.StringInput;

@Page
public class WlrServiceCodeEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public WlrServiceCodeEditForm form;
    public WlrServiceCodeEditTabs tabs;

    public static class WlrServiceCodeEditForm extends CustomWebElement {
        public StringInput id = new StringInput("form:id");
        public StringInput telecomSts = new StringInput("form:telecomSts");
    };

    public static class WlrServiceCodeEditTabs extends CustomWebElement {
    };
}