/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.btrequest;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.DateInput;
import com.optima.opticarrier.web.selenium.support.elements.EditAction;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.IntegerInput;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.StringInput;

@Page
public class BtRequestEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public BtRequestEditForm form;
    public BtRequestEditTabs tabs;

    public static class BtRequestEditForm extends CustomWebElement {
        public StringInput xml = new StringInput("form:xml");
        public StringInput status = new StringInput("form:status");
        public DateInput dateInsert = new DateInput("form:dateInsert");
        public IntegerInput fileId = new IntegerInput("form:fileId");
    };

    public static class BtRequestEditTabs extends CustomWebElement {
    };
}