/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.cpsquoteresponse;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class CpsQuoteResponseSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public CpsQuoteResponseSearchOrders orders;
    public CpsQuoteResponseSearchForm form;

    public static class CpsQuoteResponseSearchOrders extends CustomWebElement {
        public OrderBy codiceArea = new OrderBy("cpsQuoteResponse_codiceArea");
        public OrderBy descrizioneArea = new OrderBy("cpsQuoteResponse_descrizioneArea");
        public OrderBy quantitaRichesta = new OrderBy("cpsQuoteResponse_quantitaRichesta");
        public OrderBy volumiMensiliAssegnati = new OrderBy("cpsQuoteResponse_volumiMensiliAssegnati");
        public OrderBy tolleranzaMensile = new OrderBy("cpsQuoteResponse_tolleranzaMensile");
        public OrderBy volumiGiornalieriAssegnati = new OrderBy("cpsQuoteResponse_volumiGiornalieriAssegnati");
        public OrderBy tolleranzaGiornaliera = new OrderBy("cpsQuoteResponse_tolleranzaGiornaliera");
        public OrderBy giorniLavorativi = new OrderBy("cpsQuoteResponse_giorniLavorativi");
        public OrderBy fileId = new OrderBy("cpsQuoteResponse_fileId");
        public OrderBy olo = new OrderBy("cpsQuoteResponse_olo");
    }

    public static class CpsQuoteResponseSearchForm extends SearchForm {
        public Autocomplete codiceArea = new Autocomplete("form:codiceArea");
        public Autocomplete descrizioneArea = new Autocomplete("form:descrizioneArea");
        public StringRange quantitaRichesta = new StringRange("form:quantitaRichesta");
        public StringRange volumiMensiliAssegnati = new StringRange("form:volumiMensiliAssegnati");
        public StringRange tolleranzaMensile = new StringRange("form:tolleranzaMensile");
        public StringRange volumiGiornalieriAssegnati = new StringRange("form:volumiGiornalieriAssegnati");
        public StringRange tolleranzaGiornaliera = new StringRange("form:tolleranzaGiornaliera");
        public StringRange giorniLavorativi = new StringRange("form:giorniLavorativi");
        public Autocomplete file = new Autocomplete("form:fileSelector");
        public Autocomplete olo = new Autocomplete("form:oloSelector");
    }
}