/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.optima.opticarrier.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.optima.opticarrier.util.ValueGenerator;

/**
 * Basic tests for CpsDeactivationPrenotification
 */
@SuppressWarnings("unused")
public class CpsDeactivationPrenotificationTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        CpsDeactivationPrenotification model = new CpsDeactivationPrenotification();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        CpsDeactivationPrenotification model = new CpsDeactivationPrenotification();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
     public void equalsUsingPk() {
     CpsDeactivationPrenotification model1 = new CpsDeactivationPrenotification();
     CpsDeactivationPrenotification model2 = new CpsDeactivationPrenotification();

     Integer id = ValueGenerator.getUniqueInteger();
     model1.setId(id);
     model2.setId(id);

     model1.setCodiceFornitore("a");
     model2.setCodiceFornitore("a");

     model1.setCodiceOrdineFornitore("a");
     model2.setCodiceOrdineFornitore("a");

     model1.setDataNotifica(new Date());
     model2.setDataNotifica(new Date());

     model1.setDn("a");
     model2.setDn("a");

     model1.setDataSottoscrizioneContratto(new Date());
     model2.setDataSottoscrizioneContratto(new Date());

     model1.setDataPrevistaCessazione(new Date());
     model2.setDataPrevistaCessazione(new Date());

     model1.setCognomeRagSoc("a");
     model2.setCognomeRagSoc("a");

     model1.setNome("a");
     model2.setNome("a");

     model1.setDataRichiestaCessazione(new Date());
     model2.setDataRichiestaCessazione(new Date());

     model1.setStatus("dddddddddddddddddddddddddddddddddddddddddddddddddd");
     model2.setStatus("dddddddddddddddddddddddddddddddddddddddddddddddddd");
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}