/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.optima.opticarrier.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.optima.opticarrier.util.ValueGenerator;

/**
 * Basic tests for CpsQuoteRequest
 */
@SuppressWarnings("unused")
public class CpsQuoteRequestTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        CpsQuoteRequest model = new CpsQuoteRequest();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        CpsQuoteRequest model = new CpsQuoteRequest();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  CpsQuoteRequest.olo ==> OloCps.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setOlo() {
        CpsQuoteRequest many = new CpsQuoteRequest();

        // init
        OloCps one = new OloCps();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setOlo(one);

        // make sure it is propagated properly
        assertThat(many.getOlo()).isEqualTo(one);

        // now set it to back to null
        many.setOlo(null);

        // make sure null is propagated properly
        assertThat(many.getOlo()).isNull();
    }

    @Test
    public void manyToOne_setFile() {
        CpsQuoteRequest many = new CpsQuoteRequest();

        // init
        SbcFileRequest one = new SbcFileRequest();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setFile(one);

        // make sure it is propagated properly
        assertThat(many.getFile()).isEqualTo(one);

        // now set it to back to null
        many.setFile(null);

        // make sure null is propagated properly
        assertThat(many.getFile()).isNull();
    }

    /*
     public void equalsUsingPk() {
     CpsQuoteRequest model1 = new CpsQuoteRequest();
     CpsQuoteRequest model2 = new CpsQuoteRequest();

     Integer id = ValueGenerator.getUniqueInteger();
     model1.setId(id);
     model2.setId(id);

     model1.setCodiceArea(1);
     model2.setCodiceArea(1);

     model1.setDescrizioneArea("a");
     model2.setDescrizioneArea("a");

     model1.setQuantitaRichiesta(1);
     model2.setQuantitaRichiesta(1);

     model1.setMm(1);
     model2.setMm(1);

     model1.setYyyy(1);
     model2.setYyyy(1);

     model1.setStatus("a");
     model2.setStatus("a");
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}