/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.optima.opticarrier.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.optima.opticarrier.util.ValueGenerator;

/**
 * Basic tests for OloCps
 */
@SuppressWarnings("unused")
public class OloCpsTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        OloCps model = new OloCps();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        OloCps model = new OloCps();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
     public void equalsUsingPk() {
     OloCps model1 = new OloCps();
     OloCps model2 = new OloCps();

     Integer id = ValueGenerator.getUniqueInteger();
     model1.setId(id);
     model2.setId(id);

     model1.setCodiceOlo("a");
     model2.setCodiceOlo("a");

     model1.setOloDescrizione("a");
     model2.setOloDescrizione("a");

     model1.setOloDtinival(new Date());
     model2.setOloDtinival(new Date());

     model1.setOloDtfinval(new Date());
     model2.setOloDtfinval(new Date());

     model1.setCodiceTelecom("dddd");
     model2.setCodiceTelecom("dddd");
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}