/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.optima.opticarrier.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.optima.opticarrier.util.ValueGenerator;

/**
 * Basic tests for Prefissi
 */
@SuppressWarnings("unused")
public class PrefissiTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Prefissi model = new Prefissi();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Prefissi model = new Prefissi();
        model.setId(ValueGenerator.getUniqueString(15));
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
     public void equalsUsingPk() {
     Prefissi model1 = new Prefissi();
     Prefissi model2 = new Prefissi();

     String id = ValueGenerator.getUniqueString(15);
     model1.setId(id);
     model2.setId(id);

     model1.setComune("a");
     model2.setComune("a");

     model1.setProvincia("a");
     model2.setProvincia("a");

     model1.setRegione("a");
     model2.setRegione("a");

     model1.setPrefisso("a");
     model2.setPrefisso("a");

     model1.setCap("a");
     model2.setCap("a");

     model1.setCodFisco("a");
     model2.setCodFisco("a");

     model1.setAbitanti(1);
     model2.setAbitanti(1);

     model1.setLink("a");
     model2.setLink("a");
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}