/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.optima.opticarrier.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.optima.opticarrier.util.ValueGenerator;

/**
 * Basic tests for Response
 */
@SuppressWarnings("unused")
public class ResponseTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Response model = new Response();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Response model = new Response();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
     public void equalsUsingPk() {
     Response model1 = new Response();
     Response model2 = new Response();

     Integer id = ValueGenerator.getUniqueInteger();
     model1.setId(id);
     model2.setId(id);

     model1.setIdSBC(1);
     model2.setIdSBC(1);

     model1.setActionType(1);
     model2.setActionType(1);

     model1.setDataCambiamentoStato("a");
     model2.setDataCambiamentoStato("a");

     model1.setCodiceErrore("a");
     model2.setCodiceErrore("a");

     model1.setDescrizioneErrore("a");
     model2.setDescrizioneErrore("a");

     model1.setNomeFileDiOrigineRichiesta("a");
     model2.setNomeFileDiOrigineRichiesta("a");

     model1.setProgressivoRichiesta("a");
     model2.setProgressivoRichiesta("a");

     model1.setDataSpedizioneFile("a");
     model2.setDataSpedizioneFile("a");

     model1.setTipoOperazione("a");
     model2.setTipoOperazione("a");

     model1.setTipoServizio("a");
     model2.setTipoServizio("a");

     model1.setTipoLinea("a");
     model2.setTipoLinea("a");

     model1.setTipoAttivazione("a");
     model2.setTipoAttivazione("a");

     model1.setNumeroLinee("a");
     model2.setNumeroLinee("a");

     model1.setCli("a");
     model2.setCli("a");

     model1.setTipoNotifica("a");
     model2.setTipoNotifica("a");

     model1.setStatoOrdine("a");
     model2.setStatoOrdine("a");

     model1.setType("a");
     model2.setType("a");

     model1.setDn("a");
     model2.setDn("a");

     model1.setDataEsplitamento("a");
     model2.setDataEsplitamento("a");

     model1.setCodiceCausaleAnnullamento("a");
     model2.setCodiceCausaleAnnullamento("a");

     model1.setDescrizioneCausaleAnnullamento("a");
     model2.setDescrizioneCausaleAnnullamento("a");

     model1.setDataAnnullamento("a");
     model2.setDataAnnullamento("a");

     model1.setCodiceCausaleSospensione("a");
     model2.setCodiceCausaleSospensione("a");

     model1.setDescrizioneCausale("a");
     model2.setDescrizioneCausale("a");

     model1.setDataSospensione("a");
     model2.setDataSospensione("a");

     model1.setBatchId(1);
     model2.setBatchId(1);

     model1.setOloId(1);
     model2.setOloId(1);

     model1.setVariation(true);
     model2.setVariation(true);

     model1.setResponseCode("a");
     model2.setResponseCode("a");

     model1.setResponseDesc("a");
     model2.setResponseDesc("a");
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}