/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.optima.opticarrier.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.optima.opticarrier.util.ValueGenerator;

/**
 * Basic tests for SbcCpsResponse
 */
@SuppressWarnings("unused")
public class SbcCpsResponseTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        SbcCpsResponse model = new SbcCpsResponse();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        SbcCpsResponse model = new SbcCpsResponse();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  SbcCpsResponse.file ==> SbcFileResponse.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setFile() {
        SbcCpsResponse many = new SbcCpsResponse();

        // init
        SbcFileResponse one = new SbcFileResponse();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setFile(one);

        // make sure it is propagated properly
        assertThat(many.getFile()).isEqualTo(one);

        // now set it to back to null
        many.setFile(null);

        // make sure null is propagated properly
        assertThat(many.getFile()).isNull();
    }

    @Test
    public void manyToOne_setOlo() {
        SbcCpsResponse many = new SbcCpsResponse();

        // init
        OloCps one = new OloCps();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setOlo(one);

        // make sure it is propagated properly
        assertThat(many.getOlo()).isEqualTo(one);

        // now set it to back to null
        many.setOlo(null);

        // make sure null is propagated properly
        assertThat(many.getOlo()).isNull();
    }

    /*
     public void equalsUsingPk() {
     SbcCpsResponse model1 = new SbcCpsResponse();
     SbcCpsResponse model2 = new SbcCpsResponse();

     Integer id = ValueGenerator.getUniqueInteger();
     model1.setId(id);
     model2.setId(id);

     model1.setCli("a");
     model2.setCli("a");

     model1.setTipoNotifica("a");
     model2.setTipoNotifica("a");

     model1.setCodiceFornitore("a");
     model2.setCodiceFornitore("a");

     model1.setCodiceOrdineFornitore("a");
     model2.setCodiceOrdineFornitore("a");

     model1.setCodiceRichiedente("a");
     model2.setCodiceRichiedente("a");

     model1.setCodiceOrdineRichiedente("a");
     model2.setCodiceOrdineRichiedente("a");

     model1.setDataNotifica(new Date());
     model2.setDataNotifica(new Date());

     model1.setStatoOrdine("a");
     model2.setStatoOrdine("a");

     model1.setDataEspletamento(new Date());
     model2.setDataEspletamento(new Date());

     model1.setDataValidazioneFormaleContrattuale(new Date());
     model2.setDataValidazioneFormaleContrattuale(new Date());

     model1.setDataValidazioneTecnicoGestionale(new Date());
     model2.setDataValidazioneTecnicoGestionale(new Date());

     model1.setDataDro(new Date());
     model2.setDataDro(new Date());

     model1.setDataEstrazioneWl(new Date());
     model2.setDataEstrazioneWl(new Date());

     model1.setClassificazioneOrdine("a");
     model2.setClassificazioneOrdine("a");

     model1.setNote("a");
     model2.setNote("a");

     model1.setTipoCausaleRifiuto("a");
     model2.setTipoCausaleRifiuto("a");

     model1.setCodiceMotivorifiuto("a");
     model2.setCodiceMotivorifiuto("a");

     model1.setMotivoRifiuto("a");
     model2.setMotivoRifiuto("a");
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}