/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 */
package com.optima.opticarrier.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.optima.opticarrier.util.ValueGenerator;

/**
 * Basic tests for SbcCpsRequest
 */
@SuppressWarnings("unused")
public class SbcCpsRequestTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        SbcCpsRequest model = new SbcCpsRequest();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        SbcCpsRequest model = new SbcCpsRequest();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  SbcCpsRequest.file ==> SbcFileRequest.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setFile() {
        SbcCpsRequest many = new SbcCpsRequest();

        // init
        SbcFileRequest one = new SbcFileRequest();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setFile(one);

        // make sure it is propagated properly
        assertThat(many.getFile()).isEqualTo(one);

        // now set it to back to null
        many.setFile(null);

        // make sure null is propagated properly
        assertThat(many.getFile()).isNull();
    }

    @Test
    public void manyToOne_setOlo() {
        SbcCpsRequest many = new SbcCpsRequest();

        // init
        OloCps one = new OloCps();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setOlo(one);

        // make sure it is propagated properly
        assertThat(many.getOlo()).isEqualTo(one);

        // now set it to back to null
        many.setOlo(null);

        // make sure null is propagated properly
        assertThat(many.getOlo()).isNull();
    }

    @Test
    public void equalsUsingBusinessKey() {
        SbcCpsRequest model1 = new SbcCpsRequest();
        SbcCpsRequest model2 = new SbcCpsRequest();
        String requestId = ValueGenerator.getUniqueString(20);
        model1.setRequestId(requestId);
        model2.setRequestId(requestId);
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
    }
}