/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.sbccpsresponse;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class SbcCpsResponseSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public SbcCpsResponseSearchOrders orders;
    public SbcCpsResponseSearchForm form;

    public static class SbcCpsResponseSearchOrders extends CustomWebElement {
        public OrderBy cli = new OrderBy("sbcCpsResponse_cli");
        public OrderBy olo = new OrderBy("sbcCpsResponse_olo");
        public OrderBy tipoNotifica = new OrderBy("sbcCpsResponse_tipoNotifica");
        public OrderBy codiceFornitore = new OrderBy("sbcCpsResponse_codiceFornitore");
        public OrderBy codiceOrdineFornitore = new OrderBy("sbcCpsResponse_codiceOrdineFornitore");
        public OrderBy codiceRichiedente = new OrderBy("sbcCpsResponse_codiceRichiedente");
        public OrderBy codiceOrdineRichiedente = new OrderBy("sbcCpsResponse_codiceOrdineRichiedente");
        public OrderBy dataNotifica = new OrderBy("sbcCpsResponse_dataNotifica");
        public OrderBy statoOrdine = new OrderBy("sbcCpsResponse_statoOrdine");
        public OrderBy dataEspletamento = new OrderBy("sbcCpsResponse_dataEspletamento");
        public OrderBy dataValidazioneFormaleContrattuale = new OrderBy("sbcCpsResponse_dataValidazioneFormaleContrattuale");
        public OrderBy dataValidazioneTecnicoGestionale = new OrderBy("sbcCpsResponse_dataValidazioneTecnicoGestionale");
        public OrderBy dataDro = new OrderBy("sbcCpsResponse_dataDro");
        public OrderBy dataEstrazioneWl = new OrderBy("sbcCpsResponse_dataEstrazioneWl");
        public OrderBy classificazioneOrdine = new OrderBy("sbcCpsResponse_classificazioneOrdine");
        public OrderBy note = new OrderBy("sbcCpsResponse_note");
        public OrderBy tipoCausaleRifiuto = new OrderBy("sbcCpsResponse_tipoCausaleRifiuto");
        public OrderBy codiceMotivorifiuto = new OrderBy("sbcCpsResponse_codiceMotivorifiuto");
        public OrderBy motivoRifiuto = new OrderBy("sbcCpsResponse_motivoRifiuto");
        public OrderBy fileId = new OrderBy("sbcCpsResponse_fileId");
    }

    public static class SbcCpsResponseSearchForm extends SearchForm {
        public Autocomplete cli = new Autocomplete("form:cli");
        public Autocomplete tipoNotifica = new Autocomplete("form:tipoNotifica");
        public Autocomplete codiceFornitore = new Autocomplete("form:codiceFornitore");
        public Autocomplete codiceOrdineFornitore = new Autocomplete("form:codiceOrdineFornitore");
        public Autocomplete codiceRichiedente = new Autocomplete("form:codiceRichiedente");
        public Autocomplete codiceOrdineRichiedente = new Autocomplete("form:codiceOrdineRichiedente");
        public StringRange dataNotifica = new StringRange("form:dataNotifica");
        public Autocomplete statoOrdine = new Autocomplete("form:statoOrdine");
        public StringRange dataEspletamento = new StringRange("form:dataEspletamento");
        public StringRange dataValidazioneFormaleContrattuale = new StringRange("form:dataValidazioneFormaleContrattuale");
        public StringRange dataValidazioneTecnicoGestionale = new StringRange("form:dataValidazioneTecnicoGestionale");
        public StringRange dataDro = new StringRange("form:dataDro");
        public StringRange dataEstrazioneWl = new StringRange("form:dataEstrazioneWl");
        public Autocomplete classificazioneOrdine = new Autocomplete("form:classificazioneOrdine");
        public Autocomplete note = new Autocomplete("form:note");
        public Autocomplete tipoCausaleRifiuto = new Autocomplete("form:tipoCausaleRifiuto");
        public Autocomplete codiceMotivorifiuto = new Autocomplete("form:codiceMotivorifiuto");
        public Autocomplete motivoRifiuto = new Autocomplete("form:motivoRifiuto");
        public Autocomplete file = new Autocomplete("form:fileSelector");
        public Autocomplete olo = new Autocomplete("form:oloSelector");
    }
}