/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.sbcwlrrequest;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.ManyBooleans;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class SbcWlrRequestSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public SbcWlrRequestSearchOrders orders;
    public SbcWlrRequestSearchForm form;

    public static class SbcWlrRequestSearchOrders extends CustomWebElement {
        public OrderBy progressivoRichiesta = new OrderBy("sbcWlrRequest_progressivoRichiesta");
        public OrderBy actionType = new OrderBy("sbcWlrRequest_actionType");
        public OrderBy wlrType = new OrderBy("sbcWlrRequest_wlrType");
        public OrderBy dn = new OrderBy("sbcWlrRequest_dn");
        public OrderBy flagmantenimentoProdotto = new OrderBy("sbcWlrRequest_flagmantenimentoProdotto");
        public OrderBy datasottoscrizioneContratto = new OrderBy("sbcWlrRequest_datasottoscrizioneContratto");
        public OrderBy customerSurname = new OrderBy("sbcWlrRequest_customerSurname");
        public OrderBy particellaToponomastica = new OrderBy("sbcWlrRequest_particellaToponomastica");
        public OrderBy via = new OrderBy("sbcWlrRequest_via");
        public OrderBy civico = new OrderBy("sbcWlrRequest_civico");
        public OrderBy localita = new OrderBy("sbcWlrRequest_localita");
        public OrderBy codiceComune = new OrderBy("sbcWlrRequest_codiceComune");
        public OrderBy cfPiva = new OrderBy("sbcWlrRequest_cfPiva");
        public OrderBy dataDac = new OrderBy("sbcWlrRequest_dataDac");
        public OrderBy typeService = new OrderBy("sbcWlrRequest_typeService");
        public OrderBy tipeLine = new OrderBy("sbcWlrRequest_tipeLine");
        public OrderBy amount = new OrderBy("sbcWlrRequest_amount");
        public OrderBy customerPhone = new OrderBy("sbcWlrRequest_customerPhone");
        public OrderBy olo = new OrderBy("sbcWlrRequest_olo");
        public OrderBy fileId = new OrderBy("sbcWlrRequest_fileId");
        public OrderBy error = new OrderBy("sbcWlrRequest_error");
        public OrderBy rientro = new OrderBy("sbcWlrRequest_rientro");
        public OrderBy btExecuted = new OrderBy("sbcWlrRequest_btExecuted");
        public OrderBy sentToTelecom = new OrderBy("sbcWlrRequest_sentToTelecom");
    }

    public static class SbcWlrRequestSearchForm extends SearchForm {
        public Autocomplete progressivoRichiesta = new Autocomplete("form:progressivoRichiesta");
        public StringRange actionType = new StringRange("form:actionType");
        public StringRange wlrType = new StringRange("form:wlrType");
        public Autocomplete dn = new Autocomplete("form:dn");
        public StringRange flagmantenimentoProdotto = new StringRange("form:flagmantenimentoProdotto");
        public StringRange datasottoscrizioneContratto = new StringRange("form:datasottoscrizioneContratto");
        public Autocomplete customerSurname = new Autocomplete("form:customerSurname");
        public Autocomplete particellaToponomastica = new Autocomplete("form:particellaToponomastica");
        public Autocomplete via = new Autocomplete("form:via");
        public Autocomplete civico = new Autocomplete("form:civico");
        public Autocomplete localita = new Autocomplete("form:localita");
        public Autocomplete codiceComune = new Autocomplete("form:codiceComune");
        public Autocomplete cfPiva = new Autocomplete("form:cfPiva");
        public StringRange dataDac = new StringRange("form:dataDac");
        public Autocomplete typeService = new Autocomplete("form:typeService");
        public Autocomplete tipeLine = new Autocomplete("form:tipeLine");
        public StringRange amount = new StringRange("form:amount");
        public Autocomplete customerPhone = new Autocomplete("form:customerPhone");
        public Autocomplete error = new Autocomplete("form:error");
        public StringRange rientro = new StringRange("form:rientro");
        public ManyBooleans btExecuted = new ManyBooleans("form:btExecuted");
        public ManyBooleans sentToTelecom = new ManyBooleans("form:sentToTelecom");
        public Autocomplete olo = new Autocomplete("form:oloSelector");
        public Autocomplete file = new Autocomplete("form:fileSelector");
    }
}