/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.optima.opticarrier.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.CpsQuoteResponsePenali;
import com.optima.opticarrier.domain.CpsQuoteResponsePenali_;
import com.optima.opticarrier.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link CpsQuoteResponsePenali} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class CpsQuoteResponsePenaliPrinter extends GenericPrinter<CpsQuoteResponsePenali> {
    public CpsQuoteResponsePenaliPrinter() {
        super(CpsQuoteResponsePenali.class, CpsQuoteResponsePenali_.totVolRichiestiDueMesiPrec, CpsQuoteResponsePenali_.totVolAssegnatiDueMesiPrec,
                CpsQuoteResponsePenali_.totVolEffettiviDueMesiPrec);
    }

    @Override
    public String print(CpsQuoteResponsePenali cpsQuoteResponsePenali, Locale locale) {
        if (cpsQuoteResponsePenali == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, cpsQuoteResponsePenali.getTotVolRichiestiDueMesiPrec());
        appendIfNotEmpty(ret, cpsQuoteResponsePenali.getTotVolAssegnatiDueMesiPrec());
        appendIfNotEmpty(ret, cpsQuoteResponsePenali.getTotVolEffettiviDueMesiPrec());
        return ret.toString();
    }
}