/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.optima.opticarrier.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcFileRequest;
import com.optima.opticarrier.domain.SbcFileRequest_;
import com.optima.opticarrier.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link SbcFileRequest} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SbcFileRequestPrinter extends GenericPrinter<SbcFileRequest> {
    public SbcFileRequestPrinter() {
        super(SbcFileRequest.class, SbcFileRequest_.nomeFile, SbcFileRequest_.olo, SbcFileRequest_.stato);
    }

    @Override
    public String print(SbcFileRequest sbcFileRequest, Locale locale) {
        if (sbcFileRequest == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sbcFileRequest.getNomeFile());
        appendIfNotEmpty(ret, sbcFileRequest.getOlo());
        appendIfNotEmpty(ret, sbcFileRequest.getStato());
        return ret.toString();
    }
}