/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.optima.opticarrier.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcWlrRequestVariation;
import com.optima.opticarrier.domain.SbcWlrRequestVariation_;
import com.optima.opticarrier.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link SbcWlrRequestVariation} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SbcWlrRequestVariationPrinter extends GenericPrinter<SbcWlrRequestVariation> {
    public SbcWlrRequestVariationPrinter() {
        super(SbcWlrRequestVariation.class, SbcWlrRequestVariation_.progressiveRichiesta, SbcWlrRequestVariation_.dn, SbcWlrRequestVariation_.customerSurname);
    }

    @Override
    public String print(SbcWlrRequestVariation sbcWlrRequestVariation, Locale locale) {
        if (sbcWlrRequestVariation == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sbcWlrRequestVariation.getProgressiveRichiesta());
        appendIfNotEmpty(ret, sbcWlrRequestVariation.getDn());
        appendIfNotEmpty(ret, sbcWlrRequestVariation.getCustomerSurname());
        return ret.toString();
    }
}