/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 */
package com.optima.opticarrier.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.WlrServiceCode;
import com.optima.opticarrier.domain.WlrServiceCode_;
import com.optima.opticarrier.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link WlrServiceCode} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class WlrServiceCodePrinter extends GenericPrinter<WlrServiceCode> {
    public WlrServiceCodePrinter() {
        super(WlrServiceCode.class, WlrServiceCode_.telecomSts);
    }

    @Override
    public String print(WlrServiceCode wlrServiceCode, Locale locale) {
        if (wlrServiceCode == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, wlrServiceCode.getTelecomSts());
        return ret.toString();
    }
}