/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.optima.opticarrier.repository;

import java.util.Date;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.CpsDeactivationNotification;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class CpsDeactivationNotificationGenerator {

    /**
     * Returns a new CpsDeactivationNotification instance filled with random values.
     */
    public CpsDeactivationNotification getCpsDeactivationNotification() {
        CpsDeactivationNotification cpsDeactivationNotification = new CpsDeactivationNotification();

        // simple attributes follows
        cpsDeactivationNotification.setCodiceFornitore("a");
        cpsDeactivationNotification.setDataNotifica(new Date());
        cpsDeactivationNotification.setDn("a");
        cpsDeactivationNotification.setDataSottoscrizioneContratto("a");
        cpsDeactivationNotification.setCodiceMotivoRifiuto("a");
        cpsDeactivationNotification.setDataEsplitamento(new Date());
        cpsDeactivationNotification.setMotivoRifiuto("a");
        cpsDeactivationNotification.setStatus("a");
        return cpsDeactivationNotification;
    }

}