/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 */
package com.optima.opticarrier.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.optima.opticarrier.domain.OloCps;

/**
 * Integration test on OloCpsRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class OloCpsRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(OloCpsRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private OloCpsRepository oloCpsRepository;

    @Inject
    private OloCpsGenerator oloCpsGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        OloCps oloCps = oloCpsGenerator.getOloCps();

        // add it to a Set before saving (force equals/hashcode)
        Set<OloCps> set = newHashSet(oloCps, oloCps);
        assertThat(set).hasSize(1);

        oloCpsRepository.save(oloCps);
        entityManager.flush();

        // reload it from cache and check equality
        OloCps model = new OloCps();
        model.setId(oloCps.getId());
        assertThat(oloCps).isEqualTo(oloCpsRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(oloCps.getId()).isEqualTo(oloCpsRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(oloCps).isNotEqualTo(oloCpsRepository.get(model));
    }

}