/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.optima.opticarrier.repository;

import java.util.Date;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.OloCps;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class OloCpsGenerator {

    /**
     * Returns a new OloCps instance filled with random values.
     */
    public OloCps getOloCps() {
        OloCps oloCps = new OloCps();

        // simple attributes follows
        oloCps.setCodiceOlo("a");
        oloCps.setOloDescrizione("a");
        oloCps.setOloDtinival(new Date());
        oloCps.setOloDtfinval(new Date());
        oloCps.setCodiceTelecom("dddd");
        return oloCps;
    }

}