/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.optima.opticarrier.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.Prefissi;
import com.optima.opticarrier.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class PrefissiGenerator {

    /**
     * Returns a new Prefissi instance filled with random values.
     */
    public Prefissi getPrefissi() {
        Prefissi prefissi = new Prefissi();

        // primary key column must be set manually
        prefissi.setId(ValueGenerator.getUniqueString(15));
        // simple attributes follows
        prefissi.setComune("a");
        prefissi.setProvincia("a");
        prefissi.setRegione("a");
        prefissi.setPrefisso("a");
        prefissi.setCap("a");
        prefissi.setCodFisco("a");
        prefissi.setAbitanti(1);
        prefissi.setLink("a");
        return prefissi;
    }

}