/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 */
package com.optima.opticarrier.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.optima.opticarrier.domain.SbcCpsResponse;
import com.optima.opticarrier.domain.SbcCpsResponse_;
import com.optima.opticarrier.repository.support.SearchParameters;

/**
 * Integration test on SbcCpsResponseRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SbcCpsResponseRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SbcCpsResponseRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SbcCpsResponseRepository sbcCpsResponseRepository;

    @Inject
    private SbcCpsResponseGenerator sbcCpsResponseGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        SbcCpsResponse sbcCpsResponse = sbcCpsResponseGenerator.getSbcCpsResponse();

        // add it to a Set before saving (force equals/hashcode)
        Set<SbcCpsResponse> set = newHashSet(sbcCpsResponse, sbcCpsResponse);
        assertThat(set).hasSize(1);

        sbcCpsResponseRepository.save(sbcCpsResponse);
        entityManager.flush();

        // reload it from cache and check equality
        SbcCpsResponse model = new SbcCpsResponse();
        model.setId(sbcCpsResponse.getId());
        assertThat(sbcCpsResponse).isEqualTo(sbcCpsResponseRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sbcCpsResponse.getId()).isEqualTo(sbcCpsResponseRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sbcCpsResponse).isNotEqualTo(sbcCpsResponseRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        SbcCpsResponse sbcCpsResponse = sbcCpsResponseGenerator.getSbcCpsResponse();

        // add it to a Set before saving (force equals/hashcode)
        Set<SbcCpsResponse> set = newHashSet(sbcCpsResponse, sbcCpsResponse);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        sbcCpsResponse.setOlo(null);

        sbcCpsResponseRepository.save(sbcCpsResponse);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(SbcCpsResponse_.olo, (Object) null);

        List<SbcCpsResponse> elements = sbcCpsResponseRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (SbcCpsResponse element : elements) {
            assertThat(element.getOlo()).isNull();
        }
    }
}