/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.optima.opticarrier.repository;

import java.util.Date;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcCpsResponse;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class SbcCpsResponseGenerator {

    /**
     * Returns a new SbcCpsResponse instance filled with random values.
     */
    public SbcCpsResponse getSbcCpsResponse() {
        SbcCpsResponse sbcCpsResponse = new SbcCpsResponse();

        // simple attributes follows
        sbcCpsResponse.setCli("a");
        sbcCpsResponse.setTipoNotifica("a");
        sbcCpsResponse.setCodiceFornitore("a");
        sbcCpsResponse.setCodiceOrdineFornitore("a");
        sbcCpsResponse.setCodiceRichiedente("a");
        sbcCpsResponse.setCodiceOrdineRichiedente("a");
        sbcCpsResponse.setDataNotifica(new Date());
        sbcCpsResponse.setStatoOrdine("a");
        sbcCpsResponse.setDataEspletamento(new Date());
        sbcCpsResponse.setDataValidazioneFormaleContrattuale(new Date());
        sbcCpsResponse.setDataValidazioneTecnicoGestionale(new Date());
        sbcCpsResponse.setDataDro(new Date());
        sbcCpsResponse.setDataEstrazioneWl(new Date());
        sbcCpsResponse.setClassificazioneOrdine("a");
        sbcCpsResponse.setNote("a");
        sbcCpsResponse.setTipoCausaleRifiuto("a");
        sbcCpsResponse.setCodiceMotivorifiuto("a");
        sbcCpsResponse.setMotivoRifiuto("a");
        return sbcCpsResponse;
    }

}