/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 */
package com.optima.opticarrier.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.optima.opticarrier.domain.SbcFileRequest;

/**
 * Integration test on SbcFileRequestRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SbcFileRequestRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SbcFileRequestRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SbcFileRequestRepository sbcFileRequestRepository;

    @Inject
    private SbcFileRequestGenerator sbcFileRequestGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        SbcFileRequest sbcFileRequest = sbcFileRequestGenerator.getSbcFileRequest();

        // add it to a Set before saving (force equals/hashcode)
        Set<SbcFileRequest> set = newHashSet(sbcFileRequest, sbcFileRequest);
        assertThat(set).hasSize(1);

        sbcFileRequestRepository.save(sbcFileRequest);
        entityManager.flush();

        // reload it from cache and check equality
        SbcFileRequest model = new SbcFileRequest();
        model.setId(sbcFileRequest.getId());
        assertThat(sbcFileRequest).isEqualTo(sbcFileRequestRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sbcFileRequest.getId()).isEqualTo(sbcFileRequestRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sbcFileRequest).isNotEqualTo(sbcFileRequestRepository.get(model));
    }

}