/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.optima.opticarrier.repository;

import java.util.Date;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcFileResponse;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class SbcFileResponseGenerator {

    /**
     * Returns a new SbcFileResponse instance filled with random values.
     */
    public SbcFileResponse getSbcFileResponse() {
        SbcFileResponse sbcFileResponse = new SbcFileResponse();

        // simple attributes follows
        sbcFileResponse.setNomeFile("a");
        sbcFileResponse.setDataCreazione(new Date());
        sbcFileResponse.setOlo("a");
        sbcFileResponse.setStato("a");
        return sbcFileResponse;
    }

}