/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 */
package com.optima.opticarrier.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.optima.opticarrier.domain.SbcWlrRequestVariation;
import com.optima.opticarrier.domain.SbcWlrRequestVariation_;
import com.optima.opticarrier.repository.support.SearchParameters;

/**
 * Integration test on SbcWlrRequestVariationRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SbcWlrRequestVariationRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SbcWlrRequestVariationRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SbcWlrRequestVariationRepository sbcWlrRequestVariationRepository;

    @Inject
    private SbcWlrRequestVariationGenerator sbcWlrRequestVariationGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        SbcWlrRequestVariation sbcWlrRequestVariation = sbcWlrRequestVariationGenerator.getSbcWlrRequestVariation();

        // add it to a Set before saving (force equals/hashcode)
        Set<SbcWlrRequestVariation> set = newHashSet(sbcWlrRequestVariation, sbcWlrRequestVariation);
        assertThat(set).hasSize(1);

        sbcWlrRequestVariationRepository.save(sbcWlrRequestVariation);
        entityManager.flush();

        // reload it from cache and check equality
        SbcWlrRequestVariation model = new SbcWlrRequestVariation();
        model.setId(sbcWlrRequestVariation.getId());
        assertThat(sbcWlrRequestVariation).isEqualTo(sbcWlrRequestVariationRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sbcWlrRequestVariation.getId()).isEqualTo(sbcWlrRequestVariationRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sbcWlrRequestVariation).isNotEqualTo(sbcWlrRequestVariationRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        SbcWlrRequestVariation sbcWlrRequestVariation = sbcWlrRequestVariationGenerator.getSbcWlrRequestVariation();

        // add it to a Set before saving (force equals/hashcode)
        Set<SbcWlrRequestVariation> set = newHashSet(sbcWlrRequestVariation, sbcWlrRequestVariation);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        sbcWlrRequestVariation.setFile(null);

        sbcWlrRequestVariationRepository.save(sbcWlrRequestVariation);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(SbcWlrRequestVariation_.file, (Object) null);

        List<SbcWlrRequestVariation> elements = sbcWlrRequestVariationRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (SbcWlrRequestVariation element : elements) {
            assertThat(element.getFile()).isNull();
        }
    }
}