/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 */
package com.optima.opticarrier.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.TelecomFilePostfix;
import com.optima.opticarrier.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class TelecomFilePostfixGenerator {

    /**
     * Returns a new TelecomFilePostfix instance filled with random values.
     */
    public TelecomFilePostfix getTelecomFilePostfix() {
        TelecomFilePostfix telecomFilePostfix = new TelecomFilePostfix();

        // primary key column must be set manually
        telecomFilePostfix.setId(ValueGenerator.getUniqueString(8));
        // simple attributes follows
        telecomFilePostfix.setNumber(1);
        telecomFilePostfix.setOlo(1);
        telecomFilePostfix.setExtension("dddd");
        return telecomFilePostfix;
    }

}