/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.optima.opticarrier.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.CpsQuoteResponse;
import com.optima.opticarrier.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link CpsQuoteResponse} 
 */
@Named
@Singleton
public class CpsQuoteResponseRepository extends GenericRepository<CpsQuoteResponse, Integer> {

    public CpsQuoteResponseRepository() {
        super(CpsQuoteResponse.class);
    }

    @Override
    public CpsQuoteResponse getNew() {
        return new CpsQuoteResponse();
    }

    @Override
    public CpsQuoteResponse getNewWithDefaults() {
        return getNew().withDefaults();
    }
}