/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.optima.opticarrier.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.SbcFileResponse;
import com.optima.opticarrier.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link SbcFileResponse} 
 */
@Named
@Singleton
public class SbcFileResponseRepository extends GenericRepository<SbcFileResponse, Integer> {

    public SbcFileResponseRepository() {
        super(SbcFileResponse.class);
    }

    @Override
    public SbcFileResponse getNew() {
        return new SbcFileResponse();
    }

    @Override
    public SbcFileResponse getNewWithDefaults() {
        return getNew().withDefaults();
    }
}