/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.optima.opticarrier.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.WlrServiceCode;
import com.optima.opticarrier.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link WlrServiceCode} 
 */
@Named
@Singleton
public class WlrServiceCodeRepository extends GenericRepository<WlrServiceCode, String> {

    public WlrServiceCodeRepository() {
        super(WlrServiceCode.class);
    }

    @Override
    public WlrServiceCode getNew() {
        return new WlrServiceCode();
    }

    @Override
    public WlrServiceCode getNewWithDefaults() {
        return getNew().withDefaults();
    }
}