/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package com.optima.opticarrier.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.optima.opticarrier.domain.WlrTraslocoCode;
import com.optima.opticarrier.repository.support.GenericRepository;

/**
 * {@link GenericRepository} for {@link WlrTraslocoCode} 
 */
@Named
@Singleton
public class WlrTraslocoCodeRepository extends GenericRepository<WlrTraslocoCode, String> {

    public WlrTraslocoCodeRepository() {
        super(WlrTraslocoCode.class);
    }

    @Override
    public WlrTraslocoCode getNew() {
        return new WlrTraslocoCode();
    }

    @Override
    public WlrTraslocoCode getNewWithDefaults() {
        return getNew().withDefaults();
    }
}