/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/SearchPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.sbccpsrequest;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.Autocomplete;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.OrderBy;
import com.optima.opticarrier.web.selenium.support.elements.SearchForm;
import com.optima.opticarrier.web.selenium.support.elements.StringRange;
import com.optima.opticarrier.web.selenium.support.elements.Table;

@Page
public class SbcCpsRequestSearch {
    public Table table;
    public EntityAction entity;
    public Messages messages;
    public SbcCpsRequestSearchOrders orders;
    public SbcCpsRequestSearchForm form;

    public static class SbcCpsRequestSearchOrders extends CustomWebElement {
        public OrderBy cli = new OrderBy("sbcCpsRequest_cli");
        public OrderBy olo = new OrderBy("sbcCpsRequest_olo");
        public OrderBy requestId = new OrderBy("sbcCpsRequest_requestId");
        public OrderBy tipoOperazione = new OrderBy("sbcCpsRequest_tipoOperazione");
        public OrderBy tipoServizio = new OrderBy("sbcCpsRequest_tipoServizio");
        public OrderBy tipoLinea = new OrderBy("sbcCpsRequest_tipoLinea");
        public OrderBy tipoAttivazione = new OrderBy("sbcCpsRequest_tipoAttivazione");
        public OrderBy dataCreazione = new OrderBy("sbcCpsRequest_dataCreazione");
        public OrderBy numeroLinee = new OrderBy("sbcCpsRequest_numeroLinee");
        public OrderBy userInformation = new OrderBy("sbcCpsRequest_userInformation");
        public OrderBy fileId = new OrderBy("sbcCpsRequest_fileId");
        public OrderBy codiceErrore = new OrderBy("sbcCpsRequest_codiceErrore");
        public OrderBy descrizioneErrore = new OrderBy("sbcCpsRequest_descrizioneErrore");
        public OrderBy statoOrdine = new OrderBy("sbcCpsRequest_statoOrdine");
        public OrderBy tipoNotifica = new OrderBy("sbcCpsRequest_tipoNotifica");
    }

    public static class SbcCpsRequestSearchForm extends SearchForm {
        public Autocomplete cli = new Autocomplete("form:cli");
        public Autocomplete requestId = new Autocomplete("form:requestId");
        public Autocomplete tipoOperazione = new Autocomplete("form:tipoOperazione");
        public Autocomplete tipoServizio = new Autocomplete("form:tipoServizio");
        public Autocomplete tipoLinea = new Autocomplete("form:tipoLinea");
        public Autocomplete tipoAttivazione = new Autocomplete("form:tipoAttivazione");
        public StringRange dataCreazione = new StringRange("form:dataCreazione");
        public StringRange numeroLinee = new StringRange("form:numeroLinee");
        public Autocomplete userInformation = new Autocomplete("form:userInformation");
        public StringRange codiceErrore = new StringRange("form:codiceErrore");
        public Autocomplete descrizioneErrore = new Autocomplete("form:descrizioneErrore");
        public Autocomplete statoOrdine = new Autocomplete("form:statoOrdine");
        public Autocomplete tipoNotifica = new Autocomplete("form:tipoNotifica");
        public Autocomplete file = new Autocomplete("form:fileSelector");
        public Autocomplete olo = new Autocomplete("form:oloSelector");
    }
}