/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.optima.opticarrier.domain;

import static javax.persistence.TemporalType.TIMESTAMP;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;
import com.optima.opticarrier.validation.FixedLength;

@Entity
@Table(name = "CPS_DEACTIVATION_PRENOTIFICATION")
public class CpsDeactivationPrenotification implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(CpsDeactivationPrenotification.class);

    // Raw attributes
    private Integer id;
    private String codiceFornitore;
    private String codiceOrdineFornitore;
    private Date dataNotifica;
    private String dn;
    private Date dataSottoscrizioneContratto;
    private Date dataPrevistaCessazione;
    private String cognomeRagSoc;
    private String nome;
    private Date dataRichiestaCessazione;
    private String status;

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public CpsDeactivationPrenotification id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [codiceFornitore] ------------------------

    @Size(max = 20)
    @Column(name = "codiceFornitore", length = 20)
    public String getCodiceFornitore() {
        return codiceFornitore;
    }

    public void setCodiceFornitore(String codiceFornitore) {
        this.codiceFornitore = codiceFornitore;
    }

    public CpsDeactivationPrenotification codiceFornitore(String codiceFornitore) {
        setCodiceFornitore(codiceFornitore);
        return this;
    }

    // -- [codiceOrdineFornitore] ------------------------

    @Size(max = 20)
    @Column(name = "codiceOrdineFornitore", length = 20)
    public String getCodiceOrdineFornitore() {
        return codiceOrdineFornitore;
    }

    public void setCodiceOrdineFornitore(String codiceOrdineFornitore) {
        this.codiceOrdineFornitore = codiceOrdineFornitore;
    }

    public CpsDeactivationPrenotification codiceOrdineFornitore(String codiceOrdineFornitore) {
        setCodiceOrdineFornitore(codiceOrdineFornitore);
        return this;
    }

    // -- [dataNotifica] ------------------------

    @NotNull
    @Column(name = "dataNotifica", nullable = false, length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataNotifica() {
        return dataNotifica;
    }

    public void setDataNotifica(Date dataNotifica) {
        this.dataNotifica = dataNotifica;
    }

    public CpsDeactivationPrenotification dataNotifica(Date dataNotifica) {
        setDataNotifica(dataNotifica);
        return this;
    }

    // -- [dn] ------------------------

    @Size(max = 20)
    @Column(name = "dn", length = 20)
    public String getDn() {
        return dn;
    }

    public void setDn(String dn) {
        this.dn = dn;
    }

    public CpsDeactivationPrenotification dn(String dn) {
        setDn(dn);
        return this;
    }

    // -- [dataSottoscrizioneContratto] ------------------------

    @NotNull
    @Column(name = "dataSottoscrizioneContratto", nullable = false, length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataSottoscrizioneContratto() {
        return dataSottoscrizioneContratto;
    }

    public void setDataSottoscrizioneContratto(Date dataSottoscrizioneContratto) {
        this.dataSottoscrizioneContratto = dataSottoscrizioneContratto;
    }

    public CpsDeactivationPrenotification dataSottoscrizioneContratto(Date dataSottoscrizioneContratto) {
        setDataSottoscrizioneContratto(dataSottoscrizioneContratto);
        return this;
    }

    // -- [dataPrevistaCessazione] ------------------------

    @NotNull
    @Column(name = "dataPrevistaCessazione", nullable = false, length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataPrevistaCessazione() {
        return dataPrevistaCessazione;
    }

    public void setDataPrevistaCessazione(Date dataPrevistaCessazione) {
        this.dataPrevistaCessazione = dataPrevistaCessazione;
    }

    public CpsDeactivationPrenotification dataPrevistaCessazione(Date dataPrevistaCessazione) {
        setDataPrevistaCessazione(dataPrevistaCessazione);
        return this;
    }

    // -- [cognomeRagSoc] ------------------------

    @Size(max = 30)
    @Column(name = "cognomeRagSoc", length = 30)
    public String getCognomeRagSoc() {
        return cognomeRagSoc;
    }

    public void setCognomeRagSoc(String cognomeRagSoc) {
        this.cognomeRagSoc = cognomeRagSoc;
    }

    public CpsDeactivationPrenotification cognomeRagSoc(String cognomeRagSoc) {
        setCognomeRagSoc(cognomeRagSoc);
        return this;
    }

    // -- [nome] ------------------------

    @Size(max = 30)
    @Column(name = "nome", length = 30)
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public CpsDeactivationPrenotification nome(String nome) {
        setNome(nome);
        return this;
    }

    // -- [dataRichiestaCessazione] ------------------------

    @NotNull
    @Column(name = "dataRichiestaCessazione", nullable = false, length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataRichiestaCessazione() {
        return dataRichiestaCessazione;
    }

    public void setDataRichiestaCessazione(Date dataRichiestaCessazione) {
        this.dataRichiestaCessazione = dataRichiestaCessazione;
    }

    public CpsDeactivationPrenotification dataRichiestaCessazione(Date dataRichiestaCessazione) {
        setDataRichiestaCessazione(dataRichiestaCessazione);
        return this;
    }

    // -- [status] ------------------------

    @FixedLength(length = 50)
    @Column(name = "status", length = 50)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public CpsDeactivationPrenotification status(String status) {
        setStatus(status);
        return this;
    }

    /**
     * Apply the default values.
     */
    public CpsDeactivationPrenotification withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof CpsDeactivationPrenotification && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this CpsDeactivationPrenotification instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("codiceFornitore", getCodiceFornitore()) //
                .add("codiceOrdineFornitore", getCodiceOrdineFornitore()) //
                .add("dataNotifica", getDataNotifica()) //
                .add("dn", getDn()) //
                .add("dataSottoscrizioneContratto", getDataSottoscrizioneContratto()) //
                .add("dataPrevistaCessazione", getDataPrevistaCessazione()) //
                .add("cognomeRagSoc", getCognomeRagSoc()) //
                .add("nome", getNome()) //
                .add("dataRichiestaCessazione", getDataRichiestaCessazione()) //
                .add("status", getStatus()) //
                .toString();
    }
}