/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.optima.opticarrier.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "CPS_QUOTE_RESPONSE_PENALI")
public class CpsQuoteResponsePenali implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(CpsQuoteResponsePenali.class);

    // Raw attributes
    private Integer id;
    private Integer totVolRichiestiDueMesiPrec;
    private Integer totVolAssegnatiDueMesiPrec;
    private Integer totVolEffettiviDueMesiPrec;
    private Integer sogliaPenale;
    private Integer percentualePenaleApplicata;

    // Many to one
    private OloCps olo;
    private SbcFileResponse file;

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public CpsQuoteResponsePenali id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [totVolRichiestiDueMesiPrec] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "totVolRichiestiDueMesiPrec", precision = 10)
    public Integer getTotVolRichiestiDueMesiPrec() {
        return totVolRichiestiDueMesiPrec;
    }

    public void setTotVolRichiestiDueMesiPrec(Integer totVolRichiestiDueMesiPrec) {
        this.totVolRichiestiDueMesiPrec = totVolRichiestiDueMesiPrec;
    }

    public CpsQuoteResponsePenali totVolRichiestiDueMesiPrec(Integer totVolRichiestiDueMesiPrec) {
        setTotVolRichiestiDueMesiPrec(totVolRichiestiDueMesiPrec);
        return this;
    }

    // -- [totVolAssegnatiDueMesiPrec] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "totVolAssegnatiDueMesiPrec", precision = 10)
    public Integer getTotVolAssegnatiDueMesiPrec() {
        return totVolAssegnatiDueMesiPrec;
    }

    public void setTotVolAssegnatiDueMesiPrec(Integer totVolAssegnatiDueMesiPrec) {
        this.totVolAssegnatiDueMesiPrec = totVolAssegnatiDueMesiPrec;
    }

    public CpsQuoteResponsePenali totVolAssegnatiDueMesiPrec(Integer totVolAssegnatiDueMesiPrec) {
        setTotVolAssegnatiDueMesiPrec(totVolAssegnatiDueMesiPrec);
        return this;
    }

    // -- [totVolEffettiviDueMesiPrec] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "totVolEffettiviDueMesiPrec", precision = 10)
    public Integer getTotVolEffettiviDueMesiPrec() {
        return totVolEffettiviDueMesiPrec;
    }

    public void setTotVolEffettiviDueMesiPrec(Integer totVolEffettiviDueMesiPrec) {
        this.totVolEffettiviDueMesiPrec = totVolEffettiviDueMesiPrec;
    }

    public CpsQuoteResponsePenali totVolEffettiviDueMesiPrec(Integer totVolEffettiviDueMesiPrec) {
        setTotVolEffettiviDueMesiPrec(totVolEffettiviDueMesiPrec);
        return this;
    }

    // -- [sogliaPenale] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "sogliaPenale", precision = 10)
    public Integer getSogliaPenale() {
        return sogliaPenale;
    }

    public void setSogliaPenale(Integer sogliaPenale) {
        this.sogliaPenale = sogliaPenale;
    }

    public CpsQuoteResponsePenali sogliaPenale(Integer sogliaPenale) {
        setSogliaPenale(sogliaPenale);
        return this;
    }

    // -- [percentualePenaleApplicata] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "percentualePenaleApplicata", precision = 10)
    public Integer getPercentualePenaleApplicata() {
        return percentualePenaleApplicata;
    }

    public void setPercentualePenaleApplicata(Integer percentualePenaleApplicata) {
        this.percentualePenaleApplicata = percentualePenaleApplicata;
    }

    public CpsQuoteResponsePenali percentualePenaleApplicata(Integer percentualePenaleApplicata) {
        setPercentualePenaleApplicata(percentualePenaleApplicata);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: CpsQuoteResponsePenali.olo ==> OloCps.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "olo")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public OloCps getOlo() {
        return olo;
    }

    /**
     * Set the {@link #olo} without adding this CpsQuoteResponsePenali instance on the passed {@link #olo}
     */
    public void setOlo(OloCps olo) {
        this.olo = olo;
    }

    public CpsQuoteResponsePenali olo(OloCps olo) {
        setOlo(olo);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: CpsQuoteResponsePenali.file ==> SbcFileResponse.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "file_id")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public SbcFileResponse getFile() {
        return file;
    }

    /**
     * Set the {@link #file} without adding this CpsQuoteResponsePenali instance on the passed {@link #file}
     */
    public void setFile(SbcFileResponse file) {
        this.file = file;
    }

    public CpsQuoteResponsePenali file(SbcFileResponse file) {
        setFile(file);
        return this;
    }

    /**
     * Apply the default values.
     */
    public CpsQuoteResponsePenali withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof CpsQuoteResponsePenali && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this CpsQuoteResponsePenali instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("totVolRichiestiDueMesiPrec", getTotVolRichiestiDueMesiPrec()) //
                .add("totVolAssegnatiDueMesiPrec", getTotVolAssegnatiDueMesiPrec()) //
                .add("totVolEffettiviDueMesiPrec", getTotVolEffettiviDueMesiPrec()) //
                .add("sogliaPenale", getSogliaPenale()) //
                .add("percentualePenaleApplicata", getPercentualePenaleApplicata()) //
                .toString();
    }
}