/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.optima.opticarrier.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(CpsQuoteResponse.class)
public abstract class CpsQuoteResponse_ {

    // Raw attributes
    public static volatile SingularAttribute<CpsQuoteResponse, Integer> id;
    public static volatile SingularAttribute<CpsQuoteResponse, String> codiceArea;
    public static volatile SingularAttribute<CpsQuoteResponse, String> descrizioneArea;
    public static volatile SingularAttribute<CpsQuoteResponse, Integer> quantitaRichesta;
    public static volatile SingularAttribute<CpsQuoteResponse, Integer> volumiMensiliAssegnati;
    public static volatile SingularAttribute<CpsQuoteResponse, Integer> tolleranzaMensile;
    public static volatile SingularAttribute<CpsQuoteResponse, Integer> volumiGiornalieriAssegnati;
    public static volatile SingularAttribute<CpsQuoteResponse, Integer> tolleranzaGiornaliera;
    public static volatile SingularAttribute<CpsQuoteResponse, Integer> giorniLavorativi;

    // Many to one
    public static volatile SingularAttribute<CpsQuoteResponse, SbcFileResponse> file;
    public static volatile SingularAttribute<CpsQuoteResponse, OloCps> olo;
}