/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.optima.opticarrier.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "RESPONSE")
public class Response implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Response.class);

    // Raw attributes
    private Integer id;
    private Integer idSBC;
    private Integer actionType;
    private String dataCambiamentoStato;
    private String codiceErrore;
    private String descrizioneErrore;
    private String nomeFileDiOrigineRichiesta;
    private String progressivoRichiesta;
    private String dataSpedizioneFile;
    private String tipoOperazione;
    private String tipoServizio;
    private String tipoLinea;
    private String tipoAttivazione;
    private String numeroLinee;
    private String cli;
    private String tipoNotifica;
    private String statoOrdine;
    private String type;
    private String dn;
    private String dataEsplitamento;
    private String codiceCausaleAnnullamento;
    private String descrizioneCausaleAnnullamento;
    private String dataAnnullamento;
    private String codiceCausaleSospensione;
    private String descrizioneCausale;
    private String dataSospensione;
    private Integer batchId;
    private Integer oloId;
    private Boolean variation;
    private String responseCode;
    private String responseDesc;

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Response id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [idSBC] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "idSBC", precision = 10)
    public Integer getIdSBC() {
        return idSBC;
    }

    public void setIdSBC(Integer idSBC) {
        this.idSBC = idSBC;
    }

    public Response idSBC(Integer idSBC) {
        setIdSBC(idSBC);
        return this;
    }

    // -- [actionType] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "actionType", precision = 10)
    public Integer getActionType() {
        return actionType;
    }

    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }

    public Response actionType(Integer actionType) {
        setActionType(actionType);
        return this;
    }

    // -- [dataCambiamentoStato] ------------------------

    @Size(max = 50)
    @Column(name = "dataCambiamentoStato", length = 50)
    public String getDataCambiamentoStato() {
        return dataCambiamentoStato;
    }

    public void setDataCambiamentoStato(String dataCambiamentoStato) {
        this.dataCambiamentoStato = dataCambiamentoStato;
    }

    public Response dataCambiamentoStato(String dataCambiamentoStato) {
        setDataCambiamentoStato(dataCambiamentoStato);
        return this;
    }

    // -- [codiceErrore] ------------------------

    @Size(max = 50)
    @Column(name = "codiceErrore", length = 50)
    public String getCodiceErrore() {
        return codiceErrore;
    }

    public void setCodiceErrore(String codiceErrore) {
        this.codiceErrore = codiceErrore;
    }

    public Response codiceErrore(String codiceErrore) {
        setCodiceErrore(codiceErrore);
        return this;
    }

    // -- [descrizioneErrore] ------------------------

    @Size(max = 200)
    @Column(name = "descrizioneErrore", length = 200)
    public String getDescrizioneErrore() {
        return descrizioneErrore;
    }

    public void setDescrizioneErrore(String descrizioneErrore) {
        this.descrizioneErrore = descrizioneErrore;
    }

    public Response descrizioneErrore(String descrizioneErrore) {
        setDescrizioneErrore(descrizioneErrore);
        return this;
    }

    // -- [nomeFileDiOrigineRichiesta] ------------------------

    @Size(max = 50)
    @Column(name = "nomeFileDiOrigineRichiesta", length = 50)
    public String getNomeFileDiOrigineRichiesta() {
        return nomeFileDiOrigineRichiesta;
    }

    public void setNomeFileDiOrigineRichiesta(String nomeFileDiOrigineRichiesta) {
        this.nomeFileDiOrigineRichiesta = nomeFileDiOrigineRichiesta;
    }

    public Response nomeFileDiOrigineRichiesta(String nomeFileDiOrigineRichiesta) {
        setNomeFileDiOrigineRichiesta(nomeFileDiOrigineRichiesta);
        return this;
    }

    // -- [progressivoRichiesta] ------------------------

    @Size(max = 50)
    @Column(name = "progressivo_richiesta", length = 50)
    public String getProgressivoRichiesta() {
        return progressivoRichiesta;
    }

    public void setProgressivoRichiesta(String progressivoRichiesta) {
        this.progressivoRichiesta = progressivoRichiesta;
    }

    public Response progressivoRichiesta(String progressivoRichiesta) {
        setProgressivoRichiesta(progressivoRichiesta);
        return this;
    }

    // -- [dataSpedizioneFile] ------------------------

    @Size(max = 50)
    @Column(name = "dataSpedizioneFile", length = 50)
    public String getDataSpedizioneFile() {
        return dataSpedizioneFile;
    }

    public void setDataSpedizioneFile(String dataSpedizioneFile) {
        this.dataSpedizioneFile = dataSpedizioneFile;
    }

    public Response dataSpedizioneFile(String dataSpedizioneFile) {
        setDataSpedizioneFile(dataSpedizioneFile);
        return this;
    }

    // -- [tipoOperazione] ------------------------

    @Size(max = 50)
    @Column(name = "tipoOperazione", length = 50)
    public String getTipoOperazione() {
        return tipoOperazione;
    }

    public void setTipoOperazione(String tipoOperazione) {
        this.tipoOperazione = tipoOperazione;
    }

    public Response tipoOperazione(String tipoOperazione) {
        setTipoOperazione(tipoOperazione);
        return this;
    }

    // -- [tipoServizio] ------------------------

    @Size(max = 50)
    @Column(name = "tipoServizio", length = 50)
    public String getTipoServizio() {
        return tipoServizio;
    }

    public void setTipoServizio(String tipoServizio) {
        this.tipoServizio = tipoServizio;
    }

    public Response tipoServizio(String tipoServizio) {
        setTipoServizio(tipoServizio);
        return this;
    }

    // -- [tipoLinea] ------------------------

    @Size(max = 50)
    @Column(name = "tipoLinea", length = 50)
    public String getTipoLinea() {
        return tipoLinea;
    }

    public void setTipoLinea(String tipoLinea) {
        this.tipoLinea = tipoLinea;
    }

    public Response tipoLinea(String tipoLinea) {
        setTipoLinea(tipoLinea);
        return this;
    }

    // -- [tipoAttivazione] ------------------------

    @Size(max = 50)
    @Column(name = "tipoAttivazione", length = 50)
    public String getTipoAttivazione() {
        return tipoAttivazione;
    }

    public void setTipoAttivazione(String tipoAttivazione) {
        this.tipoAttivazione = tipoAttivazione;
    }

    public Response tipoAttivazione(String tipoAttivazione) {
        setTipoAttivazione(tipoAttivazione);
        return this;
    }

    // -- [numeroLinee] ------------------------

    @Size(max = 50)
    @Column(name = "numeroLinee", length = 50)
    public String getNumeroLinee() {
        return numeroLinee;
    }

    public void setNumeroLinee(String numeroLinee) {
        this.numeroLinee = numeroLinee;
    }

    public Response numeroLinee(String numeroLinee) {
        setNumeroLinee(numeroLinee);
        return this;
    }

    // -- [cli] ------------------------

    @Size(max = 50)
    @Column(name = "cli", length = 50)
    public String getCli() {
        return cli;
    }

    public void setCli(String cli) {
        this.cli = cli;
    }

    public Response cli(String cli) {
        setCli(cli);
        return this;
    }

    // -- [tipoNotifica] ------------------------

    @Size(max = 50)
    @Column(name = "tipoNotifica", length = 50)
    public String getTipoNotifica() {
        return tipoNotifica;
    }

    public void setTipoNotifica(String tipoNotifica) {
        this.tipoNotifica = tipoNotifica;
    }

    public Response tipoNotifica(String tipoNotifica) {
        setTipoNotifica(tipoNotifica);
        return this;
    }

    // -- [statoOrdine] ------------------------

    @Size(max = 50)
    @Column(name = "statoOrdine", length = 50)
    public String getStatoOrdine() {
        return statoOrdine;
    }

    public void setStatoOrdine(String statoOrdine) {
        this.statoOrdine = statoOrdine;
    }

    public Response statoOrdine(String statoOrdine) {
        setStatoOrdine(statoOrdine);
        return this;
    }

    // -- [type] ------------------------

    @Size(max = 3)
    @Column(name = "`type`", length = 3)
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Response type(String type) {
        setType(type);
        return this;
    }

    // -- [dn] ------------------------

    @Size(max = 30)
    @Column(name = "dn", length = 30)
    public String getDn() {
        return dn;
    }

    public void setDn(String dn) {
        this.dn = dn;
    }

    public Response dn(String dn) {
        setDn(dn);
        return this;
    }

    // -- [dataEsplitamento] ------------------------

    @Size(max = 30)
    @Column(name = "dataEsplitamento", length = 30)
    public String getDataEsplitamento() {
        return dataEsplitamento;
    }

    public void setDataEsplitamento(String dataEsplitamento) {
        this.dataEsplitamento = dataEsplitamento;
    }

    public Response dataEsplitamento(String dataEsplitamento) {
        setDataEsplitamento(dataEsplitamento);
        return this;
    }

    // -- [codiceCausaleAnnullamento] ------------------------

    @Size(max = 30)
    @Column(name = "codiceCausaleAnnullamento", length = 30)
    public String getCodiceCausaleAnnullamento() {
        return codiceCausaleAnnullamento;
    }

    public void setCodiceCausaleAnnullamento(String codiceCausaleAnnullamento) {
        this.codiceCausaleAnnullamento = codiceCausaleAnnullamento;
    }

    public Response codiceCausaleAnnullamento(String codiceCausaleAnnullamento) {
        setCodiceCausaleAnnullamento(codiceCausaleAnnullamento);
        return this;
    }

    // -- [descrizioneCausaleAnnullamento] ------------------------

    @Size(max = 30)
    @Column(name = "descrizioneCausaleAnnullamento", length = 30)
    public String getDescrizioneCausaleAnnullamento() {
        return descrizioneCausaleAnnullamento;
    }

    public void setDescrizioneCausaleAnnullamento(String descrizioneCausaleAnnullamento) {
        this.descrizioneCausaleAnnullamento = descrizioneCausaleAnnullamento;
    }

    public Response descrizioneCausaleAnnullamento(String descrizioneCausaleAnnullamento) {
        setDescrizioneCausaleAnnullamento(descrizioneCausaleAnnullamento);
        return this;
    }

    // -- [dataAnnullamento] ------------------------

    @Size(max = 30)
    @Column(name = "dataAnnullamento", length = 30)
    public String getDataAnnullamento() {
        return dataAnnullamento;
    }

    public void setDataAnnullamento(String dataAnnullamento) {
        this.dataAnnullamento = dataAnnullamento;
    }

    public Response dataAnnullamento(String dataAnnullamento) {
        setDataAnnullamento(dataAnnullamento);
        return this;
    }

    // -- [codiceCausaleSospensione] ------------------------

    @Size(max = 30)
    @Column(name = "codiceCausaleSospensione", length = 30)
    public String getCodiceCausaleSospensione() {
        return codiceCausaleSospensione;
    }

    public void setCodiceCausaleSospensione(String codiceCausaleSospensione) {
        this.codiceCausaleSospensione = codiceCausaleSospensione;
    }

    public Response codiceCausaleSospensione(String codiceCausaleSospensione) {
        setCodiceCausaleSospensione(codiceCausaleSospensione);
        return this;
    }

    // -- [descrizioneCausale] ------------------------

    @Size(max = 30)
    @Column(name = "descrizioneCausale", length = 30)
    public String getDescrizioneCausale() {
        return descrizioneCausale;
    }

    public void setDescrizioneCausale(String descrizioneCausale) {
        this.descrizioneCausale = descrizioneCausale;
    }

    public Response descrizioneCausale(String descrizioneCausale) {
        setDescrizioneCausale(descrizioneCausale);
        return this;
    }

    // -- [dataSospensione] ------------------------

    @Size(max = 30)
    @Column(name = "dataSospensione", length = 30)
    public String getDataSospensione() {
        return dataSospensione;
    }

    public void setDataSospensione(String dataSospensione) {
        this.dataSospensione = dataSospensione;
    }

    public Response dataSospensione(String dataSospensione) {
        setDataSospensione(dataSospensione);
        return this;
    }

    // -- [batchId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "batchId", precision = 10)
    public Integer getBatchId() {
        return batchId;
    }

    public void setBatchId(Integer batchId) {
        this.batchId = batchId;
    }

    public Response batchId(Integer batchId) {
        setBatchId(batchId);
        return this;
    }

    // -- [oloId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "olo_id", precision = 10)
    public Integer getOloId() {
        return oloId;
    }

    public void setOloId(Integer oloId) {
        this.oloId = oloId;
    }

    public Response oloId(Integer oloId) {
        setOloId(oloId);
        return this;
    }

    // -- [variation] ------------------------

    @Column(name = "variation", length = 1)
    public Boolean getVariation() {
        return variation;
    }

    public void setVariation(Boolean variation) {
        this.variation = variation;
    }

    public Response variation(Boolean variation) {
        setVariation(variation);
        return this;
    }

    // -- [responseCode] ------------------------

    @Size(max = 255)
    @Column(name = "response_code")
    public String getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }

    public Response responseCode(String responseCode) {
        setResponseCode(responseCode);
        return this;
    }

    // -- [responseDesc] ------------------------

    @Size(max = 255)
    @Column(name = "response_desc")
    public String getResponseDesc() {
        return responseDesc;
    }

    public void setResponseDesc(String responseDesc) {
        this.responseDesc = responseDesc;
    }

    public Response responseDesc(String responseDesc) {
        setResponseDesc(responseDesc);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Response withDefaults() {
        setVariation(false);
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Response && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Response instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("idSBC", getIdSBC()) //
                .add("actionType", getActionType()) //
                .add("dataCambiamentoStato", getDataCambiamentoStato()) //
                .add("codiceErrore", getCodiceErrore()) //
                .add("descrizioneErrore", getDescrizioneErrore()) //
                .add("nomeFileDiOrigineRichiesta", getNomeFileDiOrigineRichiesta()) //
                .add("progressivoRichiesta", getProgressivoRichiesta()) //
                .add("dataSpedizioneFile", getDataSpedizioneFile()) //
                .add("tipoOperazione", getTipoOperazione()) //
                .add("tipoServizio", getTipoServizio()) //
                .add("tipoLinea", getTipoLinea()) //
                .add("tipoAttivazione", getTipoAttivazione()) //
                .add("numeroLinee", getNumeroLinee()) //
                .add("cli", getCli()) //
                .add("tipoNotifica", getTipoNotifica()) //
                .add("statoOrdine", getStatoOrdine()) //
                .add("type", getType()) //
                .add("dn", getDn()) //
                .add("dataEsplitamento", getDataEsplitamento()) //
                .add("codiceCausaleAnnullamento", getCodiceCausaleAnnullamento()) //
                .add("descrizioneCausaleAnnullamento", getDescrizioneCausaleAnnullamento()) //
                .add("dataAnnullamento", getDataAnnullamento()) //
                .add("codiceCausaleSospensione", getCodiceCausaleSospensione()) //
                .add("descrizioneCausale", getDescrizioneCausale()) //
                .add("dataSospensione", getDataSospensione()) //
                .add("batchId", getBatchId()) //
                .add("oloId", getOloId()) //
                .add("variation", getVariation()) //
                .add("responseCode", getResponseCode()) //
                .add("responseDesc", getResponseDesc()) //
                .toString();
    }
}