/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.optima.opticarrier.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.TIMESTAMP;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;

@Entity
@Table(name = "SBC_CPS_RESPONSE")
public class SbcCpsResponse implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(SbcCpsResponse.class);

    // Raw attributes
    private Integer id;
    private String cli;
    private String tipoNotifica;
    private String codiceFornitore;
    private String codiceOrdineFornitore;
    private String codiceRichiedente;
    private String codiceOrdineRichiedente;
    private Date dataNotifica;
    private String statoOrdine;
    private Date dataEspletamento;
    private Date dataValidazioneFormaleContrattuale;
    private Date dataValidazioneTecnicoGestionale;
    private Date dataDro;
    private Date dataEstrazioneWl;
    private String classificazioneOrdine;
    private String note;
    private String tipoCausaleRifiuto;
    private String codiceMotivorifiuto;
    private String motivoRifiuto;

    // Many to one
    private SbcFileResponse file;
    private OloCps olo;

    // -- [id] ------------------------

    @Override
    @Column(name = "cps_id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public SbcCpsResponse id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [cli] ------------------------

    @NotEmpty
    @Size(max = 15)
    @Column(name = "cli", nullable = false, length = 15)
    public String getCli() {
        return cli;
    }

    public void setCli(String cli) {
        this.cli = cli;
    }

    public SbcCpsResponse cli(String cli) {
        setCli(cli);
        return this;
    }

    // -- [tipoNotifica] ------------------------

    @NotEmpty
    @Size(max = 30)
    @Column(name = "tipo_notifica", nullable = false, length = 30)
    public String getTipoNotifica() {
        return tipoNotifica;
    }

    public void setTipoNotifica(String tipoNotifica) {
        this.tipoNotifica = tipoNotifica;
    }

    public SbcCpsResponse tipoNotifica(String tipoNotifica) {
        setTipoNotifica(tipoNotifica);
        return this;
    }

    // -- [codiceFornitore] ------------------------

    @Size(max = 20)
    @Column(name = "codice_fornitore", length = 20)
    public String getCodiceFornitore() {
        return codiceFornitore;
    }

    public void setCodiceFornitore(String codiceFornitore) {
        this.codiceFornitore = codiceFornitore;
    }

    public SbcCpsResponse codiceFornitore(String codiceFornitore) {
        setCodiceFornitore(codiceFornitore);
        return this;
    }

    // -- [codiceOrdineFornitore] ------------------------

    @Size(max = 20)
    @Column(name = "codice_ordine_fornitore", length = 20)
    public String getCodiceOrdineFornitore() {
        return codiceOrdineFornitore;
    }

    public void setCodiceOrdineFornitore(String codiceOrdineFornitore) {
        this.codiceOrdineFornitore = codiceOrdineFornitore;
    }

    public SbcCpsResponse codiceOrdineFornitore(String codiceOrdineFornitore) {
        setCodiceOrdineFornitore(codiceOrdineFornitore);
        return this;
    }

    // -- [codiceRichiedente] ------------------------

    @Size(max = 20)
    @Column(name = "codice_richiedente", length = 20)
    public String getCodiceRichiedente() {
        return codiceRichiedente;
    }

    public void setCodiceRichiedente(String codiceRichiedente) {
        this.codiceRichiedente = codiceRichiedente;
    }

    public SbcCpsResponse codiceRichiedente(String codiceRichiedente) {
        setCodiceRichiedente(codiceRichiedente);
        return this;
    }

    // -- [codiceOrdineRichiedente] ------------------------

    @Size(max = 20)
    @Column(name = "codice_ordine_richiedente", length = 20)
    public String getCodiceOrdineRichiedente() {
        return codiceOrdineRichiedente;
    }

    public void setCodiceOrdineRichiedente(String codiceOrdineRichiedente) {
        this.codiceOrdineRichiedente = codiceOrdineRichiedente;
    }

    public SbcCpsResponse codiceOrdineRichiedente(String codiceOrdineRichiedente) {
        setCodiceOrdineRichiedente(codiceOrdineRichiedente);
        return this;
    }

    // -- [dataNotifica] ------------------------

    @Column(name = "data_notifica", length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataNotifica() {
        return dataNotifica;
    }

    public void setDataNotifica(Date dataNotifica) {
        this.dataNotifica = dataNotifica;
    }

    public SbcCpsResponse dataNotifica(Date dataNotifica) {
        setDataNotifica(dataNotifica);
        return this;
    }

    // -- [statoOrdine] ------------------------

    @Size(max = 50)
    @Column(name = "stato_ordine", length = 50)
    public String getStatoOrdine() {
        return statoOrdine;
    }

    public void setStatoOrdine(String statoOrdine) {
        this.statoOrdine = statoOrdine;
    }

    public SbcCpsResponse statoOrdine(String statoOrdine) {
        setStatoOrdine(statoOrdine);
        return this;
    }

    // -- [dataEspletamento] ------------------------

    @Column(name = "data_espletamento", length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataEspletamento() {
        return dataEspletamento;
    }

    public void setDataEspletamento(Date dataEspletamento) {
        this.dataEspletamento = dataEspletamento;
    }

    public SbcCpsResponse dataEspletamento(Date dataEspletamento) {
        setDataEspletamento(dataEspletamento);
        return this;
    }

    // -- [dataValidazioneFormaleContrattuale] ------------------------

    @Column(name = "data_validazione_formale_contrattuale", length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataValidazioneFormaleContrattuale() {
        return dataValidazioneFormaleContrattuale;
    }

    public void setDataValidazioneFormaleContrattuale(Date dataValidazioneFormaleContrattuale) {
        this.dataValidazioneFormaleContrattuale = dataValidazioneFormaleContrattuale;
    }

    public SbcCpsResponse dataValidazioneFormaleContrattuale(Date dataValidazioneFormaleContrattuale) {
        setDataValidazioneFormaleContrattuale(dataValidazioneFormaleContrattuale);
        return this;
    }

    // -- [dataValidazioneTecnicoGestionale] ------------------------

    @Column(name = "data_validazione_tecnico_gestionale", length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataValidazioneTecnicoGestionale() {
        return dataValidazioneTecnicoGestionale;
    }

    public void setDataValidazioneTecnicoGestionale(Date dataValidazioneTecnicoGestionale) {
        this.dataValidazioneTecnicoGestionale = dataValidazioneTecnicoGestionale;
    }

    public SbcCpsResponse dataValidazioneTecnicoGestionale(Date dataValidazioneTecnicoGestionale) {
        setDataValidazioneTecnicoGestionale(dataValidazioneTecnicoGestionale);
        return this;
    }

    // -- [dataDro] ------------------------

    @Column(name = "data_DRO", length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataDro() {
        return dataDro;
    }

    public void setDataDro(Date dataDro) {
        this.dataDro = dataDro;
    }

    public SbcCpsResponse dataDro(Date dataDro) {
        setDataDro(dataDro);
        return this;
    }

    // -- [dataEstrazioneWl] ------------------------

    @Column(name = "data_estrazione_WL", length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataEstrazioneWl() {
        return dataEstrazioneWl;
    }

    public void setDataEstrazioneWl(Date dataEstrazioneWl) {
        this.dataEstrazioneWl = dataEstrazioneWl;
    }

    public SbcCpsResponse dataEstrazioneWl(Date dataEstrazioneWl) {
        setDataEstrazioneWl(dataEstrazioneWl);
        return this;
    }

    // -- [classificazioneOrdine] ------------------------

    @Size(max = 50)
    @Column(name = "classificazione_ordine", length = 50)
    public String getClassificazioneOrdine() {
        return classificazioneOrdine;
    }

    public void setClassificazioneOrdine(String classificazioneOrdine) {
        this.classificazioneOrdine = classificazioneOrdine;
    }

    public SbcCpsResponse classificazioneOrdine(String classificazioneOrdine) {
        setClassificazioneOrdine(classificazioneOrdine);
        return this;
    }

    // -- [note] ------------------------

    @Size(max = 255)
    @Column(name = "note")
    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public SbcCpsResponse note(String note) {
        setNote(note);
        return this;
    }

    // -- [tipoCausaleRifiuto] ------------------------

    @Size(max = 50)
    @Column(name = "tipo_causale_rifiuto", length = 50)
    public String getTipoCausaleRifiuto() {
        return tipoCausaleRifiuto;
    }

    public void setTipoCausaleRifiuto(String tipoCausaleRifiuto) {
        this.tipoCausaleRifiuto = tipoCausaleRifiuto;
    }

    public SbcCpsResponse tipoCausaleRifiuto(String tipoCausaleRifiuto) {
        setTipoCausaleRifiuto(tipoCausaleRifiuto);
        return this;
    }

    // -- [codiceMotivorifiuto] ------------------------

    @Size(max = 10)
    @Column(name = "codice_motivorifiuto", length = 10)
    public String getCodiceMotivorifiuto() {
        return codiceMotivorifiuto;
    }

    public void setCodiceMotivorifiuto(String codiceMotivorifiuto) {
        this.codiceMotivorifiuto = codiceMotivorifiuto;
    }

    public SbcCpsResponse codiceMotivorifiuto(String codiceMotivorifiuto) {
        setCodiceMotivorifiuto(codiceMotivorifiuto);
        return this;
    }

    // -- [motivoRifiuto] ------------------------

    @Size(max = 100)
    @Column(name = "motivo_rifiuto", length = 100)
    public String getMotivoRifiuto() {
        return motivoRifiuto;
    }

    public void setMotivoRifiuto(String motivoRifiuto) {
        this.motivoRifiuto = motivoRifiuto;
    }

    public SbcCpsResponse motivoRifiuto(String motivoRifiuto) {
        setMotivoRifiuto(motivoRifiuto);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: SbcCpsResponse.file ==> SbcFileResponse.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "file_id")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public SbcFileResponse getFile() {
        return file;
    }

    /**
     * Set the {@link #file} without adding this SbcCpsResponse instance on the passed {@link #file}
     */
    public void setFile(SbcFileResponse file) {
        this.file = file;
    }

    public SbcCpsResponse file(SbcFileResponse file) {
        setFile(file);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: SbcCpsResponse.olo ==> OloCps.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "olo")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public OloCps getOlo() {
        return olo;
    }

    /**
     * Set the {@link #olo} without adding this SbcCpsResponse instance on the passed {@link #olo}
     */
    public void setOlo(OloCps olo) {
        this.olo = olo;
    }

    public SbcCpsResponse olo(OloCps olo) {
        setOlo(olo);
        return this;
    }

    /**
     * Apply the default values.
     */
    public SbcCpsResponse withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SbcCpsResponse && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this SbcCpsResponse instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("cli", getCli()) //
                .add("tipoNotifica", getTipoNotifica()) //
                .add("codiceFornitore", getCodiceFornitore()) //
                .add("codiceOrdineFornitore", getCodiceOrdineFornitore()) //
                .add("codiceRichiedente", getCodiceRichiedente()) //
                .add("codiceOrdineRichiedente", getCodiceOrdineRichiedente()) //
                .add("dataNotifica", getDataNotifica()) //
                .add("statoOrdine", getStatoOrdine()) //
                .add("dataEspletamento", getDataEspletamento()) //
                .add("dataValidazioneFormaleContrattuale", getDataValidazioneFormaleContrattuale()) //
                .add("dataValidazioneTecnicoGestionale", getDataValidazioneTecnicoGestionale()) //
                .add("dataDro", getDataDro()) //
                .add("dataEstrazioneWl", getDataEstrazioneWl()) //
                .add("classificazioneOrdine", getClassificazioneOrdine()) //
                .add("note", getNote()) //
                .add("tipoCausaleRifiuto", getTipoCausaleRifiuto()) //
                .add("codiceMotivorifiuto", getCodiceMotivorifiuto()) //
                .add("motivoRifiuto", getMotivoRifiuto()) //
                .toString();
    }
}