/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 */
package com.optima.opticarrier.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.TemporalType.TIMESTAMP;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.Objects;
import com.optima.opticarrier.validation.FixedLength;

@Entity
@Table(name = "SBC_CPS_REQUEST")
public class SbcCpsRequest implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(SbcCpsRequest.class);

    // Raw attributes
    private Integer id;
    private String cli;
    private String requestId;
    private String tipoOperazione;
    private String tipoServizio;
    private String tipoLinea;
    private String tipoAttivazione;
    private Date dataCreazione;
    private Integer numeroLinee;
    private String userInformation;
    private Integer codiceErrore;
    private String descrizioneErrore;
    private String statoOrdine;
    private String tipoNotifica;

    // Many to one
    private SbcFileRequest file;
    private OloCps olo;

    // -- [id] ------------------------

    @Override
    @Column(name = "cps_id", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public SbcCpsRequest id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [cli] ------------------------

    @NotEmpty
    @Size(max = 15)
    @Column(name = "cli", nullable = false, length = 15)
    public String getCli() {
        return cli;
    }

    public void setCli(String cli) {
        this.cli = cli;
    }

    public SbcCpsRequest cli(String cli) {
        setCli(cli);
        return this;
    }

    // -- [requestId] ------------------------

    @Size(max = 20)
    @Column(name = "request_id", unique = true, length = 20)
    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public SbcCpsRequest requestId(String requestId) {
        setRequestId(requestId);
        return this;
    }

    // -- [tipoOperazione] ------------------------

    @FixedLength(length = 1)
    @Column(name = "tipo_operazione", length = 1)
    public String getTipoOperazione() {
        return tipoOperazione;
    }

    public void setTipoOperazione(String tipoOperazione) {
        this.tipoOperazione = tipoOperazione;
    }

    public SbcCpsRequest tipoOperazione(String tipoOperazione) {
        setTipoOperazione(tipoOperazione);
        return this;
    }

    // -- [tipoServizio] ------------------------

    @Size(max = 20)
    @Column(name = "tipo_servizio", length = 20)
    public String getTipoServizio() {
        return tipoServizio;
    }

    public void setTipoServizio(String tipoServizio) {
        this.tipoServizio = tipoServizio;
    }

    public SbcCpsRequest tipoServizio(String tipoServizio) {
        setTipoServizio(tipoServizio);
        return this;
    }

    // -- [tipoLinea] ------------------------

    @Size(max = 20)
    @Column(name = "tipo_linea", length = 20)
    public String getTipoLinea() {
        return tipoLinea;
    }

    public void setTipoLinea(String tipoLinea) {
        this.tipoLinea = tipoLinea;
    }

    public SbcCpsRequest tipoLinea(String tipoLinea) {
        setTipoLinea(tipoLinea);
        return this;
    }

    // -- [tipoAttivazione] ------------------------

    @Size(max = 20)
    @Column(name = "tipo_attivazione", length = 20)
    public String getTipoAttivazione() {
        return tipoAttivazione;
    }

    public void setTipoAttivazione(String tipoAttivazione) {
        this.tipoAttivazione = tipoAttivazione;
    }

    public SbcCpsRequest tipoAttivazione(String tipoAttivazione) {
        setTipoAttivazione(tipoAttivazione);
        return this;
    }

    // -- [dataCreazione] ------------------------

    @Column(name = "data_creazione", length = 19)
    @Temporal(TIMESTAMP)
    public Date getDataCreazione() {
        return dataCreazione;
    }

    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    public SbcCpsRequest dataCreazione(Date dataCreazione) {
        setDataCreazione(dataCreazione);
        return this;
    }

    // -- [numeroLinee] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "numero_linee", precision = 10)
    public Integer getNumeroLinee() {
        return numeroLinee;
    }

    public void setNumeroLinee(Integer numeroLinee) {
        this.numeroLinee = numeroLinee;
    }

    public SbcCpsRequest numeroLinee(Integer numeroLinee) {
        setNumeroLinee(numeroLinee);
        return this;
    }

    // -- [userInformation] ------------------------

    @Size(max = 200)
    @Column(name = "user_information", length = 200)
    public String getUserInformation() {
        return userInformation;
    }

    public void setUserInformation(String userInformation) {
        this.userInformation = userInformation;
    }

    public SbcCpsRequest userInformation(String userInformation) {
        setUserInformation(userInformation);
        return this;
    }

    // -- [codiceErrore] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "codice_errore", precision = 10)
    public Integer getCodiceErrore() {
        return codiceErrore;
    }

    public void setCodiceErrore(Integer codiceErrore) {
        this.codiceErrore = codiceErrore;
    }

    public SbcCpsRequest codiceErrore(Integer codiceErrore) {
        setCodiceErrore(codiceErrore);
        return this;
    }

    // -- [descrizioneErrore] ------------------------

    @FixedLength(length = 250)
    @Column(name = "descrizione_errore", length = 250)
    public String getDescrizioneErrore() {
        return descrizioneErrore;
    }

    public void setDescrizioneErrore(String descrizioneErrore) {
        this.descrizioneErrore = descrizioneErrore;
    }

    public SbcCpsRequest descrizioneErrore(String descrizioneErrore) {
        setDescrizioneErrore(descrizioneErrore);
        return this;
    }

    // -- [statoOrdine] ------------------------

    @Size(max = 50)
    @Column(name = "stato_ordine", length = 50)
    public String getStatoOrdine() {
        return statoOrdine;
    }

    public void setStatoOrdine(String statoOrdine) {
        this.statoOrdine = statoOrdine;
    }

    public SbcCpsRequest statoOrdine(String statoOrdine) {
        setStatoOrdine(statoOrdine);
        return this;
    }

    // -- [tipoNotifica] ------------------------

    @Size(max = 30)
    @Column(name = "tipo_notifica", length = 30)
    public String getTipoNotifica() {
        return tipoNotifica;
    }

    public void setTipoNotifica(String tipoNotifica) {
        this.tipoNotifica = tipoNotifica;
    }

    public SbcCpsRequest tipoNotifica(String tipoNotifica) {
        setTipoNotifica(tipoNotifica);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: SbcCpsRequest.file ==> SbcFileRequest.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "file_id")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public SbcFileRequest getFile() {
        return file;
    }

    /**
     * Set the {@link #file} without adding this SbcCpsRequest instance on the passed {@link #file}
     */
    public void setFile(SbcFileRequest file) {
        this.file = file;
    }

    public SbcCpsRequest file(SbcFileRequest file) {
        setFile(file);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: SbcCpsRequest.olo ==> OloCps.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "olo")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public OloCps getOlo() {
        return olo;
    }

    /**
     * Set the {@link #olo} without adding this SbcCpsRequest instance on the passed {@link #olo}
     */
    public void setOlo(OloCps olo) {
        this.olo = olo;
    }

    public SbcCpsRequest olo(OloCps olo) {
        setOlo(olo);
        return this;
    }

    /**
     * Apply the default values.
     */
    public SbcCpsRequest withDefaults() {
        setNumeroLinee(0);
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SbcCpsRequest && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getRequestId());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warn("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefuly review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this SbcCpsRequest instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return Objects.toStringHelper(this) //
                .add("id", getId()) //
                .add("cli", getCli()) //
                .add("requestId", getRequestId()) //
                .add("tipoOperazione", getTipoOperazione()) //
                .add("tipoServizio", getTipoServizio()) //
                .add("tipoLinea", getTipoLinea()) //
                .add("tipoAttivazione", getTipoAttivazione()) //
                .add("dataCreazione", getDataCreazione()) //
                .add("numeroLinee", getNumeroLinee()) //
                .add("userInformation", getUserInformation()) //
                .add("codiceErrore", getCodiceErrore()) //
                .add("descrizioneErrore", getDescrizioneErrore()) //
                .add("statoOrdine", getStatoOrdine()) //
                .add("tipoNotifica", getTipoNotifica()) //
                .toString();
    }
}