/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.optima.opticarrier.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SbcCpsRequest.class)
public abstract class SbcCpsRequest_ {

    // Raw attributes
    public static volatile SingularAttribute<SbcCpsRequest, Integer> id;
    public static volatile SingularAttribute<SbcCpsRequest, String> cli;
    public static volatile SingularAttribute<SbcCpsRequest, String> requestId;
    public static volatile SingularAttribute<SbcCpsRequest, String> tipoOperazione;
    public static volatile SingularAttribute<SbcCpsRequest, String> tipoServizio;
    public static volatile SingularAttribute<SbcCpsRequest, String> tipoLinea;
    public static volatile SingularAttribute<SbcCpsRequest, String> tipoAttivazione;
    public static volatile SingularAttribute<SbcCpsRequest, Date> dataCreazione;
    public static volatile SingularAttribute<SbcCpsRequest, Integer> numeroLinee;
    public static volatile SingularAttribute<SbcCpsRequest, String> userInformation;
    public static volatile SingularAttribute<SbcCpsRequest, Integer> codiceErrore;
    public static volatile SingularAttribute<SbcCpsRequest, String> descrizioneErrore;
    public static volatile SingularAttribute<SbcCpsRequest, String> statoOrdine;
    public static volatile SingularAttribute<SbcCpsRequest, String> tipoNotifica;

    // Many to one
    public static volatile SingularAttribute<SbcCpsRequest, SbcFileRequest> file;
    public static volatile SingularAttribute<SbcCpsRequest, OloCps> olo;
}