/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.optima.opticarrier.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SbcWlrRequest.class)
public abstract class SbcWlrRequest_ {

    // Raw attributes
    public static volatile SingularAttribute<SbcWlrRequest, Integer> id;
    public static volatile SingularAttribute<SbcWlrRequest, String> progressivoRichiesta;
    public static volatile SingularAttribute<SbcWlrRequest, Integer> actionType;
    public static volatile SingularAttribute<SbcWlrRequest, Integer> wlrType;
    public static volatile SingularAttribute<SbcWlrRequest, String> dn;
    public static volatile SingularAttribute<SbcWlrRequest, Integer> flagmantenimentoProdotto;
    public static volatile SingularAttribute<SbcWlrRequest, Date> datasottoscrizioneContratto;
    public static volatile SingularAttribute<SbcWlrRequest, String> customerSurname;
    public static volatile SingularAttribute<SbcWlrRequest, String> particellaToponomastica;
    public static volatile SingularAttribute<SbcWlrRequest, String> via;
    public static volatile SingularAttribute<SbcWlrRequest, String> civico;
    public static volatile SingularAttribute<SbcWlrRequest, String> localita;
    public static volatile SingularAttribute<SbcWlrRequest, String> codiceComune;
    public static volatile SingularAttribute<SbcWlrRequest, String> cfPiva;
    public static volatile SingularAttribute<SbcWlrRequest, Date> dataDac;
    public static volatile SingularAttribute<SbcWlrRequest, String> typeService;
    public static volatile SingularAttribute<SbcWlrRequest, String> tipeLine;
    public static volatile SingularAttribute<SbcWlrRequest, Integer> amount;
    public static volatile SingularAttribute<SbcWlrRequest, String> customerPhone;
    public static volatile SingularAttribute<SbcWlrRequest, String> error;
    public static volatile SingularAttribute<SbcWlrRequest, Date> creationDate;
    public static volatile SingularAttribute<SbcWlrRequest, Integer> rientro;
    public static volatile SingularAttribute<SbcWlrRequest, Boolean> btExecuted;
    public static volatile SingularAttribute<SbcWlrRequest, Boolean> sentToTelecom;

    // Many to one
    public static volatile SingularAttribute<SbcWlrRequest, OloCps> olo;
    public static volatile SingularAttribute<SbcWlrRequest, SbcFileRequest> file;
}