/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.optima.opticarrier.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SbcWlrRequestVariation.class)
public abstract class SbcWlrRequestVariation_ {

    // Raw attributes
    public static volatile SingularAttribute<SbcWlrRequestVariation, Integer> id;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> progressiveRichiesta;
    public static volatile SingularAttribute<SbcWlrRequestVariation, Integer> actionType;
    public static volatile SingularAttribute<SbcWlrRequestVariation, Integer> wlrType;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> dn;
    public static volatile SingularAttribute<SbcWlrRequestVariation, Date> dataSottoscrizioneContratto;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> customerSurname;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> serviceNumber;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> numberAdditional;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> codicePrestazione;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> aggiuntivo1;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> aggiuntivo2;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> aggiuntivo3;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> aggiuntivo4;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> aggiuntivo5;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> aggiuntivo6;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> aggiuntivo7;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> codeMove;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> lineNumber;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> directionality;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> codeDriveType;
    public static volatile SingularAttribute<SbcWlrRequestVariation, String> status;
    public static volatile SingularAttribute<SbcWlrRequestVariation, Integer> waits;
    public static volatile SingularAttribute<SbcWlrRequestVariation, Boolean> elaborated;

    // Many to one
    public static volatile SingularAttribute<SbcWlrRequestVariation, OloCps> olo;
    public static volatile SingularAttribute<SbcWlrRequestVariation, SbcFileRequest> file;
}