/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-selenium-primefaces:src/test/java/selenium/pages/entity/EditPage.e.vm.java
 */
package com.optima.opticarrier.web.selenium.page.cpsdeactivationprenotification;

import com.optima.opticarrier.web.selenium.support.Page;
import com.optima.opticarrier.web.selenium.support.elements.CustomWebElement;
import com.optima.opticarrier.web.selenium.support.elements.DateInput;
import com.optima.opticarrier.web.selenium.support.elements.EditAction;
import com.optima.opticarrier.web.selenium.support.elements.EntityAction;
import com.optima.opticarrier.web.selenium.support.elements.Messages;
import com.optima.opticarrier.web.selenium.support.elements.StringInput;

@Page
public class CpsDeactivationPrenotificationEdit {
    public EditAction action;
    public Messages messages;
    public EntityAction entity;
    public CpsDeactivationPrenotificationEditForm form;
    public CpsDeactivationPrenotificationEditTabs tabs;

    public static class CpsDeactivationPrenotificationEditForm extends CustomWebElement {
        public StringInput codiceFornitore = new StringInput("form:codiceFornitore");
        public StringInput codiceOrdineFornitore = new StringInput("form:codiceOrdineFornitore");
        public DateInput dataNotifica = new DateInput("form:dataNotifica");
        public StringInput dn = new StringInput("form:dn");
        public DateInput dataSottoscrizioneContratto = new DateInput("form:dataSottoscrizioneContratto");
        public DateInput dataPrevistaCessazione = new DateInput("form:dataPrevistaCessazione");
        public StringInput cognomeRagSoc = new StringInput("form:cognomeRagSoc");
        public StringInput nome = new StringInput("form:nome");
        public DateInput dataRichiestaCessazione = new DateInput("form:dataRichiestaCessazione");
        public StringInput status = new StringInput("form:status");
    };

    public static class CpsDeactivationPrenotificationEditTabs extends CustomWebElement {
    };
}